TreeSet简单实现
ecodeclub/ekit pull request #159
Opened 2023-02-23 14:30 UTC by yzicheng

基于TreeMap实现TreeSet 红黑树增加KeyValues方法用于遍历树节点信息

2023-02-24 09:02 UTC, longyue0521 requested changes

2023-02-24 15:03 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +	midOrder[K, V](rb.root, func(k K, v V) {
好的，我修改下方法

2023-02-24 15:04 UTC, yzicheng commented on internal/tree/red_black_tree_test.go
> +			name:      "node-empty",
这里name写错

2023-02-24 15:27 UTC, yzicheng commented on set/treeset.go
> +// Keys 方法返回的元素顺序从小到大
好的，的确注释不够严谨，返回顺序是不固定。

2023-02-25 03:08 UTC, longyue0521 requested changes

2023-02-25 14:37 UTC, flycash requested changes

2023-02-25 14:37 UTC, flycash commented on set/treeset.go
> +type TreeSet[T comparable] struct {
在我们使用 Comparator 的基础下，这里泛型约束应该是 any 而不是 comparable。因为我们可以预期，使用 TreeSet 的地方反而大多数情况下都不是 comparable 的

2023-02-25 14:37 UTC, flycash commented on set/treeset_test.go
> +			treeSet, _ := NewTreeSet[int](compare())
这边检测一下 err，用 require，防止将来有人改了 NewTreeSet 这里没反应

2023-02-25 14:37 UTC, flycash commented on set/treeset_test.go
> +			treeSet, _ := NewTreeSet[int](compare())
其它测试里面也类似

2023-02-27 01:44 UTC, longyue0521 approved these changes

2023-03-02 02:32 UTC, flycash approved these changes

2023-03-02 02:32 UTC, merged