完成areapool的最基本功能
ecodeclub/ekit pull request #160
Opened 2023-03-04 05:14 UTC by jason12360

- GET,PUT,FREE
- 暂时不支持并发

2023-03-06 02:23 UTC, flycash requested changes
把它做成线程安全的，然后后面我们考虑替换成在 list 里面实现的无锁的 list 来放所有的元素

2023-03-06 02:23 UTC, flycash commented on pool/areana_pool_test.go
> +package pool
这里要加一个 //go:build goexperiment.arenas，对应的测试文件也要加。每个文件的 Apache 证书不要忘了

2023-03-06 02:23 UTC, flycash commented on pool/areana_pool_test.go
> +}
这里两个测试用不上，删掉

2023-03-06 02:23 UTC, flycash commented on pool/areana_pool_test.go
> +func TestArenaPool(t *testing.T) {
ArenaPool 的测试用例设计要考虑：
- Pool 原本没有任何元素，取走，会出发创建
- Pool 里面有元素，取走

2023-03-06 02:23 UTC, flycash commented on pool/arena_pool.go
> +type ArenaPool struct {
设计成泛型结构：
```go
ArenaPool[T any]
```

2023-03-06 02:23 UTC, flycash commented on pool/arena_pool.go
> +type ArenaPool struct {
后面的New方法之类的都要引入泛型参数

2023-03-06 02:23 UTC, flycash commented on pool/arena_pool.go
> +func NewArenaPool(new func() any) *ArenaPool {
new 是关键字，换一个名字

2023-03-06 02:23 UTC, flycash commented on pool/arena_pool.go
> +	Cursor int
做成私有的

2023-03-06 02:23 UTC, flycash commented on pool/arena_pool.go
> +	memMap map[string]*arena.Arena
这个用不上删掉

2023-03-06 02:24 UTC, flycash commented on pool/arena_pool.go
> +	Object any
能不能删掉这个字段？我有点好奇，按照道理来说，我们持有了 Mem 就应该算是可以了

2023-03-06 02:29 UTC, flycash commented
后续要考虑：
- 性能测试。目前来看最简单的并发做法就是读写锁
- 内存使用量控制，以及相应的淘汰设计
- 可观测性，即暴露内部缓存了多少元素，占用了多少空间之类的

2023-03-06 02:31 UTC, flycash commented on pool/arena_pool.go
> +func (b *Box) Free() error {
这个方法也不要暴露了，用户不应该自己控制是否 Free，不然我们内部容易出错

2023-03-06 02:33 UTC, jason12360 commented on pool/arena_pool.go
> +	Object any
这个object表示用户new出来的东西啊。

2023-03-09 07:20 UTC, flycash reviewed
你是忘记推代码了？

2023-03-13 03:07 UTC, flycash requested changes

2023-03-13 03:07 UTC, flycash commented on pool/areana_pool_test.go
> +var count int
不要定义这种包变量

2023-03-13 03:07 UTC, flycash commented on pool/areana_pool_test.go
> +var count int
你把整个 count，Test 和 NewTest 都放进去测试方法里面，用闭包的写法。包变量的可测性极差，互相之间有影响

2023-03-13 03:07 UTC, flycash commented on pool/arena_pool.go
> +}
这样相当于你直接创建了一个新对象，而这个新对象没有放进去 Arena 里面

2023-03-13 03:07 UTC, flycash commented on pool/arena_pool.go
> +type ArenaPool[T any] struct {
整个 Pool 做成并发安全的。基本上所有的使用场景都是在并发环境里面

2023-03-13 03:07 UTC, flycash commented on pool/arena_pool.go
> +}
box 被放进去了 arena 里面，但是 object 没有。object 依旧被 GC 管着

2023-03-13 03:07 UTC, flycash commented on pool/arena_pool.go
> +}
我觉得应该是：
```go
func (a *ArenaPool[T]) newX() (*Box[T], error) {
	mem := arena.NewArena()
	box := &Box{}
	box.Mem = mem
	box.object = arena.New[T](mem)
	return box, nil
}
```

2023-03-13 14:10 UTC, flycash requested changes
- 在 .Changelog 里面加一条，把这个合并请求加进去
- 执行一下 make check，主要就是要格式化一下代码

2023-03-13 14:10 UTC, flycash commented on pool/areana_pool_test.go
> +// Copyright 2021 gotomicro
license 的头部，你看看别的文件，我们应该改用 ecodeclub 来作为组织了

2023-03-14 02:50 UTC, flycash approved these changes

2023-03-14 03:30 UTC, merged