WIP: TaskPool 的可观测性
ecodeclub/ekit pull request #165
Opened 2023-03-12 05:06 UTC by Stone-afk

2023-03-13 03:21 UTC, flycash reviewed
MetricTask 我比较倾向于让用户自己的去设计。我们这边暂时不需要提供。
我觉得我们需要在 TaskPool 里面增加一个返回 channel 的方法，就是那个 chan event 的方法。

那么目前暂时暴露第一种 Event，就是 TaskPool 内部状态。

我现在的基本想法是：
- 和单独一个 Task 相关的度量，让用户通过类似于 MetricTask 的封装，自己去解决；
- 整个 TaskPool，或者 Task 和 TaskPool 交互产生的状态，就由我们来暴露；

我在想，如果我们不暴露非常通用的 Events 方法，而是暴露一个：
```go
type TaskPool interface {
     Stats() (chan State, error)
}
```
从扩展性上来说很差，但是我们是否真的需要 Event 这种通用的抽象。比如说将来是否真的会暴露类似于 TaskWaitingTimeout 之类的 Event。
@longyue0521 你觉得呢？

2023-03-13 03:21 UTC, flycash commented on pool/observer.go
> +}
这个没有特别大的意义，因为一个 TaskPool 运行起来就是很久的。

2023-03-13 06:11 UTC, longyue0521 commented
@flycash  @Stone-afk 

1. 关于MetricTask我们可以给用户打个样或者用Example的形式指导用户如何自定义MetricTask
2. 关于用State还是Event,我的想法是我们一起罗列出具体可观测的内容并给出精准的定义,然后划分边界
    - 哪些是**单独一个 Task 相关的度量**
      - 比如,Task的运行时间——从进入Task.run方法开始,到离开run方法的时间; Task的运行状态——正常运行结束/ctx超时
    - 哪些是**整个 TaskPool或者 Task 和 TaskPool 交互产生的状态**
      - Task的等待调度时间,从Task被提交到TaskPool开始算起,到分配go协程或者到马上Task.Run之前为止
      - Task的运行状态 —— 正常结束(无法区分Task是否为ctx超时结束),异常结束,TaskPool要关闭被是被取消了等
3. 有了上面精确定义的观测内容和边界,我们就能确定实现难度以及这个观测内容是否必要.这样选Event还是State就没那么难了了

2023-03-13 08:46 UTC, Stone-afk commented
@flycash @longyue0521 
有部分 TaskPool或者 Task 和 TaskPool 交互产生的状态，例如：等待调度时间、运行状态，用 Stats() (chan State, error) 方法解决不了，因为该方法只是针对整个 TaskPool 相关的指标

2023-03-13 12:29 UTC, flycash commented
> 

我仔细想了一下，任务跟 TaskPool 的交互了，也就是等待调度这个一个可能会比较重要。如果我们将来引入了等待超时就不调度的机制，那么这个也有点重要。但是核心还是在于说，我们目前的监控——比如说我以前对线程池的监控，其实主要是监控线程池本身的状态，比如说线程池有多少活跃线程，有多少任务在队列中。

至于任务等了多久之类的都从来没有监控过。

另外一方面来说，跟任务有关的状态，用户都可以通过自己使用装饰器的模式来达成目标。即便是在队列里面长期等待这种等待时长也是可行的。

那么我现在觉得，如果我们只考虑暴露 TaskPool 本身的状态，也就是 goroutine 数量、等待任务数量，队列大小，差不多就可以了。

那么我们可以暴露一个  Stats 方法。

> 哪些是单独一个 Task 相关的度量
> 比如,Task的运行时间——从进入Task.run方法开始,到离开run方法的时间; Task的运行状态——正常运行结束/ctx超时
> 哪些是整个 TaskPool或者 Task 和 TaskPool 交互产生的状态
> Task的等待调度时间,从Task被提交到TaskPool开始算起,到分配go协程或者到马上Task.Run之前为止
> Task的运行状态 —— 正常结束(无法区分Task是否为ctx超时结束),异常结束,TaskPool要关闭被是被取消了等

这些，都是用户可以通过装饰器解决的。用户解决不了的，就是我说，池子自身的状态。

2023-03-13 12:34 UTC, flycash commented
Stats 方法就是缺了一点扩展性。

2023-03-26 02:03 UTC, flycash requested changes

2023-03-26 02:03 UTC, flycash commented on pool/task_pool.go
> +	b.statsOnce.Do(func() {
用不上这个

2023-03-26 02:03 UTC, flycash commented on pool/task_pool.go
> +	StatsChan chan State
用不上这个

2023-03-26 02:03 UTC, flycash commented on pool/task_pool.go
> +func (b *OnDemandBlockTaskPool) Stats(ctx context.Context, internal time.Duration) (<-chan State, error) {
你在这边返回的就应该是局部创建的 channel

2023-03-26 02:03 UTC, flycash commented on pool/task_pool.go
> +				}
这边加一个 default 分支就可以。也就是说，如果用户有处理状态信息，并且速度可以，那么你就能发送成功，不然的话你就直接丢弃。也就是两个分支，<- State 和 default 分支

2023-03-26 02:03 UTC, flycash commented on pool/task_pool.go
> +					WaitingTaskCnt: len(b.queue),
注意线程安全

2023-03-26 04:02 UTC, Stone-afk commented on pool/task_pool.go
> +				}
这里同样需要考虑  ctx.Done() 和 shutdownNowCtx.Done() 吧

2023-03-26 04:14 UTC, Stone-afk commented on pool/task_pool.go
> +				}
丢弃了要考虑重试逻辑吗，不重试的话要等下一次的执行时间

2023-03-26 04:30 UTC, Stone-afk commented on pool/task_pool.go
> +				}
<img width="981" alt="image" src="https://user-images.githubusercontent.com/73482944/227755380-f77fac6c-90e5-4e7c-864b-14ef0792d9d2.png">
如果是考虑直接丢弃的话，就加上注释

2023-03-26 10:44 UTC, flycash commented on pool/task_pool.go
> +				}
在 Stats 方法上加注释就可以。

2023-03-26 10:46 UTC, flycash commented on pool/task_pool.go
> +				}
直接丢弃是基于这样一种考虑：
正常来说，用户消费这个 State 是很快的，大概就是记录一下日志上报一下 tracing 之类的，所以不太可能阻塞；而如果阻塞了，就会遇到一个问题，那就是 Stats 本身是一个时效性很强的方法，比如说当前采用的数据，跑到下一个周期再发送出去，意义就不大了，所以直接丢弃；最后一个理由则是，这种可观测性，大多数时候即便丢了一点数据也没关系，无关痛痒。

2023-03-27 13:50 UTC, Stone-afk commented
@flycash @longyue0521

2023-03-28 07:16 UTC, longyue0521 requested changes

2023-03-28 07:16 UTC, longyue0521 commented on pool/types.go
> +	States(ctx context.Context, internal time.Duration) (<-chan State, error)
States语义不明，@flycash  @Stone-afk 需要讨论一下：

1. 是想表示“States 定期获取TaskPool运行期间内部状态（定期采样）”的意思吗？为什么加ctx？
2. “如果在ctx过期都没提交成功，那么应该返回错误” 提交成功是什么意思？
3. internal -> interval，interval表示获取TaskPool运行期间内部状态的周期/时间间隔

2023-03-28 07:16 UTC, longyue0521 commented on pool/types.go
> +}
1. PoolState应该具有描述性，Running/Stopped；如果State结构体只用来获取RUNNING状态下TaskPool的内部状态信息，我觉得PoolState可以去掉并将State结构体改为RunningState
2. GoCnt改为goroutines？
4. WaitingTaskCnt 表示等待中的任务数，改为 tasksInWaiting？
5. RunningTasksCnt 表示运行中的任务数，改为tasksInRunning？

2023-03-28 07:49 UTC, longyue0521 requested changes

2023-03-28 07:49 UTC, longyue0521 commented on pool/task_pool.go
> +	}
1. 首先你要明确该方法在TaskPool不同状态下的表现，以及进入该方法的前置状态，离开该方法时的后置状态，如果前后置状态不一致，那么说明该方法会导致TaskPool状态迁移，还需要考虑其他方法是否受影响；如果前后置状态一致，那么该方法就相当于在前置状态下，抢一个时间片来采样。
2. 去看一下Submit方法中的trySubmit方法，你需要“锁”住TaskPool的状态然后再采样

2023-03-28 07:49 UTC, longyue0521 commented on pool/task_pool.go
> +	}
这段代码是不是可以合并到开启的go协程中

2023-03-28 07:49 UTC, longyue0521 commented on pool/task_pool.go
> +	return statsChan, nil
这个error没有作用啊，启动的协程大概率还没运行呢父协程就走到`if err !=nil`（还可能会出现读写并发问题），所以说States的API中error表示的是“是否获取chan State成功” 而不是”在采样期间发生错误”（要实现这样的效果你需要加参数，要么在API返回值列表上加，要么在State结构体上加）

2023-03-29 03:11 UTC, flycash requested changes

2023-03-29 03:11 UTC, flycash commented on pool/types.go
> +	States(ctx context.Context, internal time.Duration) (<-chan State, error)
- ctx 的意思是让用户来控制什么时候退出采样。那么最基本的两个退出机制：一个是 ctx 被 cancel 了或者超时了，一个是TaskPool 被关闭了
- 写错了？不需要提交
- error 仅仅表示创建 chan state 是否成功

这里依旧有一个问题，就是类似于整个 pool 级别的 error，目前并没有很好的处理机制。单一的任务的 error 可以要求用户自己用装饰器来处理，但是整个 pool该怎么办？
- 直接 log 下来：比如说要求用户传入一个 log 函数
- 再来一个 error channel？ 还是说在 State 里面带一个 chan error？

2023-03-29 03:11 UTC, flycash commented on pool/types.go
> +}
1. 我觉得没必要限制在只能获得 running 时候的状态。

后面几个命名我觉得我都能接受，@Stone-afk 你自己决定就行。

2023-03-29 03:11 UTC, flycash commented on pool/task_pool.go
> +	select {
这个可以直接删掉，就是 Stats 调用的那一刻，是否返回状态其实不太重要。然后 statsChan 一定是没有缓存的。

这里有这样一个隐患，就是如果这个东西带缓存，那么缓存-取走之间有一个时间差，那么就会导致它拿到的Stats 已经不准了

2023-03-29 03:11 UTC, flycash commented on pool/types.go
> +type State struct {
在这里加一个时间戳，就是采用的时间，也就是 ticker.C 返回的那个

2023-03-29 03:11 UTC, flycash commented on pool/task_pool.go
> +		return nil, fmt.Errorf("%w", errTaskPoolIsClosing)
采样的时候，我觉得没必要管这些状态，所以可以去掉。这样子也不需要“锁”住状态。

2023-03-29 03:11 UTC, flycash commented on pool/types.go
> +	States(ctx context.Context, internal time.Duration) (<-chan State, error)
ctx 用于控制采样。当 ctx 被取消或者超时的时候，就会退出采样。

2023-03-29 03:11 UTC, flycash commented on pool/types.go
> +	States(ctx context.Context, internal time.Duration) (<-chan State, error)
应该是，ctx.Done 会退出采用，或者池子被彻底关闭（也就是优雅退出也结束）了也会退出采样

2023-03-29 03:11 UTC, flycash commented on pool/task_pool.go
> +				return
这两个退出之前，都立刻上报一次 State。这样用户可以在结束之前获得结束那个时刻的状态。不太准就是

2023-03-29 03:28 UTC, longyue0521 commented on pool/types.go
> +}
1. PoolState是数字,不具备描述性
2. 明确一下States()可以哪种状态下的pool进行采样以及pool方法(并发)调用顺序问题. 
    - 刚创建出来的pool是created,只能提交Task这时会否有意义、是否允许调用States? 
    - 在pool处于Running状态下调用States返回chan, 此后pool状态迁移至closing/stopped, 只是简单地close(chan state)还是要对告知调用者关闭的原因?ctx超时,pool被关闭?
    - 在pool处于Closing/Stopped状态下,调用States是否有意义?是否允许?

2023-03-29 03:35 UTC, longyue0521 commented on pool/types.go
> +}
WaitingTaskCnt 和 RunningTasksCnt 统一一下

2023-03-31 13:26 UTC, Stone-afk reviewed
mark

2023-04-02 02:00 UTC, Stone-afk commented on pool/types.go
> +}
如果不打算限制在只能获得 某一种 时候的状态， 我理解应该是任何一种状态都应该允许被调用。

2023-04-02 02:34 UTC, Stone-afk commented on pool/task_pool.go
> +	}
这里要考虑进入临界区失败怎么办，重试？如果在 goroutine 中进入临界区失败呢，如何返回报错，还是继续重试

2023-04-02 02:55 UTC, longyue0521 commented on pool/task_pool.go
> +	}
上面提到在任何状态下都允许采样，这里就不要考虑是否进入临界区了，只是PoolState的值可能为locked即锁住的状态；

2023-04-02 09:04 UTC, flycash requested changes

2023-04-02 09:04 UTC, flycash commented on pool/task_pool.go
> +			default:
在有 default 分支的情况下，每次进来这个 for 循环，如果 ticker 没有触发，直接就 default。又进入下一个循环，那么最终效果就接近于一种无限循环了，空耗 CPU。所以这边去掉 default 分支后，那么其它三个分支就会阻塞，这样就不会空转了。

2023-04-02 09:13 UTC, flycash commented on pool/types.go
> +}
不用做这种限制。因为即便调用了，对用户来说也没有损失。

2023-04-02 09:17 UTC, Stone-afk commented on pool/task_pool.go
> +			default:
done

2023-04-02 09:28 UTC, flycash requested changes

2023-04-02 09:28 UTC, flycash commented on pool/task_pool.go
> +	statsChan := make(chan State, 1)
我之前说过一次的就是这里，不能设置任何的容量，不然用户取出来的数据就可能不够及时。

2023-04-02 09:28 UTC, flycash commented on pool/task_pool.go
> +		b.sendState(statsChan, time.Now().UnixNano())
在没有容量的情况下，这一句在大多数情况下，都没有效果，因为用户都还没拿到 statsChan 你这里就执行了

2023-04-02 09:36 UTC, Stone-afk commented on pool/task_pool.go
> +		b.sendState(statsChan, time.Now().UnixNano())
我这一句的假设有容量的，这个步骤本来不在 ch 里面，如果没有这个步骤，那么用户需要调用 State 方法后经过 internal 时间后，才能收到第一个 state 实例，也就只有这种场景 ch 不设容量才行

2023-04-02 09:38 UTC, flycash commented on pool/task_pool.go
> +		b.sendState(statsChan, time.Now().UnixNano())
我觉得不是特别需要立刻拿到一个状态。比如说我的采用周期是五秒，那么我觉得五秒后拿到状态好像也没什么。即便我是一分钟采用一次，一分钟之后我拿到状态，也没什么问题？

2023-04-02 09:47 UTC, flycash requested changes

2023-04-02 09:47 UTC, flycash commented on pool/task_pool.go
> +		Stamp:           stamp,
改名叫做 Timestamp 吧。时间戳时间戳，不是戳

2023-04-02 09:52 UTC, flycash approved these changes
@longyue0521 有空看看

2023-04-02 10:08 UTC, flycash commented
测试崩了！

2023-04-02 10:44 UTC, longyue0521 requested changes

2023-04-02 10:44 UTC, longyue0521 commented on pool/types.go
> +	States(ctx context.Context, internal time.Duration) (<-chan State, error)
之前提过的拼写错误：internal -> interval

2023-04-02 10:44 UTC, longyue0521 commented on pool/types.go
> +	RunningTasksCnt int32
之前提过的一致性问题：RunningTasksCnt 中Task后面有s，WaitingTaskCnt  中 Task后面没有s ，统一一下

2023-04-02 10:44 UTC, longyue0521 commented on pool/task_pool.go
> +func (b *OnDemandBlockTaskPool) States(ctx context.Context, internal time.Duration) (<-chan State, error) {
internal -> interval

2023-04-02 10:44 UTC, longyue0521 commented on pool/task_pool.go
> +func (b *OnDemandBlockTaskPool) getState(timeStamp int64) State {
把getState方法移动到sendState后面，这样阅读States起来方便点。

2023-04-02 10:44 UTC, longyue0521 commented on pool/task_pool.go
> +	defer b.mutex.RUnlock()
最小化锁时间，b.mutex保护的只有b.totalGo，故加锁后将b.totalGo放在局部变量totalGo内然后立即解锁。

复用 b.numOfGo()方法

2023-04-02 10:44 UTC, longyue0521 commented on pool/task_pool.go
> +	}
为什么要做这个判断？什么场景下numGoRunningTasks会出现小于0的情况？

2023-04-02 10:57 UTC, Stone-afk commented on pool/task_pool.go
> +	}
stoped

2023-04-02 10:58 UTC, Stone-afk commented on pool/task_pool.go
> +	}
关闭前

2023-04-02 11:56 UTC, longyue0521 commented on pool/task_pool.go
> +	}
在任何时候 numGoRunningTasks 都应该是>= 0的，所以去掉`runningTasks < 0`这个判断

然后，试着将goroutine方法中的判断语句

```go
if atomic.CompareAndSwapInt32(&b.numGoRunningTasks, 1, 0) && atomic.LoadInt32(&b.state) == stateClosing{
``` 
改为 
```go
if atomic.LoadInt32(&b.state) == stateClosing && atomic.CompareAndSwapInt32(&b.numGoRunningTasks, 1, 0) {
// 就是对调一下两个判断语句顺序
```
看看能否修复numGoRunningTasks < 0的问题，如果不能将测试用例给一下。

2023-04-02 12:50 UTC, Stone-afk commented on pool/task_pool.go
> +	defer b.mutex.RUnlock()
按理说 队列也需要受锁的保护
```
QueueSize:       cap(b.queue),
		WaitingTaskCnt:  len(b.queue),

```

2023-04-02 13:54 UTC, longyue0521 commented on pool/task_pool.go
> +	defer b.mutex.RUnlock()
沿着你的“理”进一步推理一下，b.queue <- x、<-b.queue、select { case <- b.queue}等 是不是也需要受锁的保护？ 如果不需要，大家都是对chan的操作，都会被转化为runtime内部相应的函数/方法的调用，为什么cap和len需要？

在设计ADT时，所有方法在实现其对外宣称的功能的同时，也需要维护ADT内部的不变性，而”并发安全与否“通常是最基本的不变性。以并发队列ADT为例，确立了”并发安全“不变性后还需要维护”先进先出“这个不变性。 只要有一个不满足，就可以说这个并发队列是不正确的/不满足需求的。而破坏”并发安全“不变性的方法之一就是一部分方法是并发安全的，一部分方法不是，有时也称这种情况为不变性不是”封闭“的。

2023-04-02 15:36 UTC, flycash commented on pool/task_pool.go
> +	defer b.mutex.RUnlock()
如果只需要保护 b.totalGo，那么就直接原子操作就可以了。都不需要加锁解锁了

2023-04-03 00:35 UTC, longyue0521 commented on pool/task_pool.go
> +	defer b.mutex.RUnlock()
如果要精准地获取b.totalGo，只能加锁不能用原子操作，在goroutine方法中执行完task.Run后有一个调整b.totalGo在那个区间的策略，这个是基于锁而不是原子操作来实现。原子操作和锁虽然各自都能保证并发安全但两者混用会有问题

2023-04-03 10:02 UTC, longyue0521 requested changes

2023-04-03 10:02 UTC, longyue0521 commented on pool/task_pool_test.go
> +	}
睡5秒，上面的TaskFunc任务都执行完了，这不与不添加任何任务直接p.Start()等价吗？sleep之后调p.States想表明什么意图？

2023-04-03 12:39 UTC, flycash requested changes

2023-04-03 12:39 UTC, flycash commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
实际上我觉得这里面真正可能的问题是一致性。也就是说因为它里面每一个步骤都是原子操作，所以实际上可能读完一个字段的时候，另外一个字段已经发生了变化。

即便是加上读锁也并没有办法，因为有些字段是脱离了读锁的控制的。

2023-04-03 12:39 UTC, flycash commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
所以，暂且就这样，即便不一致（不是某个固定时间点的状态），我认为对于一个观测者来说，不会影响他做决策

2023-04-03 12:39 UTC, flycash commented on pool/task_pool_test.go
> +			//}
不需要就删掉

2023-04-03 12:39 UTC, flycash commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
我也认为拆成 subtest 的形式会比 table driven 的形式更好，因为这边 table driven 要求所有的测试用例都 sleep 有点奇怪。

2023-04-04 04:25 UTC, Stone-afk commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
t.Run 不就已经是  subtest 了吗

2023-04-04 06:48 UTC, longyue0521 commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
你现在的t.Run是以subtest的形式定义的”模板“，通过tc中的参数来填充”模板“最终形成测试；这里的问题是不管测试场景是否合适该”模板“都要硬塞进来，为此还会做很多奇奇怪怪的兼容/适配——就是那条`time.Sleep(tc.stopDuration)`或者其他条件语句。可读性非常差，所以根据情况要么拆成`len(testCases)`个独立的子测试，要么将不适合该”模板“的场景单独拆出来写独立的子测试。虽然麻烦点，但是可读性、可理解性、可维护性更好。

你可以参考同文件下的其他测试，基本上都是以单独的子测试来实现的，并没有用table driven + ”模板“的方式。

2023-04-04 12:24 UTC, flycash commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
其实 table driven 一般用来处理只有输入输出不一样的。而你这里是需要控制比较复杂的退出机制，所以不适合用 table driven，不然就会有 longyue0521 说的问题，因为要使用统一的模板，而不得不引入一些奇怪的代码

2023-04-04 12:24 UTC, flycash commented on pool/task_pool_test.go
> +			time.Sleep(tc.stopDuration)
直接
```go
func TestXXX(t ) {

    t.Run(xxx, func())
    
    t.Run(xxx, func())
}
```
类似于这样。

2023-04-05 04:42 UTC, Stone-afk commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
```
func testTaskPoolStatesCtxTimeout(t *testing.T, pool *OnDemandBlockTaskPool, wantState State) {
	done := make(chan struct{})
	err := pool.Submit(context.Background(), TaskFunc(func(ctx context.Context) error {
		<-done
		return nil
	}))
	assert.NoError(t, err)
	err = pool.Submit(context.Background(), TaskFunc(func(ctx context.Context) error {
		<-done
		return nil
	}))
	assert.NoError(t, err)

	n := cap(pool.queue) - 2
	eg := new(errgroup.Group)

	for i := 0; i < n; i++ {
		eg.Go(func() error {
			return pool.Submit(context.Background(), TaskFunc(func(ctx context.Context) error {
				<-done
				return nil
			}))
		})
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	ch, err := pool.States(ctx, time.Millisecond)
	assert.NoError(t, err)
	cancel()
	state1 := <-ch
	assert.Equal(t, wantState, state1)

	state2, ok := <-ch
	if ok {
		assert.Equal(t, wantState, state2)
	} else {
		assert.False(t, ok)
	}
	
	_ = eg.Wait()
	close(done)
}
```
大佬，你看这样大致思路对嘛

2023-04-05 04:46 UTC, Stone-afk commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
这个貌似测不了 ctx 采样超时，ctx 采样超时应该就是调用 State 方法的时候就返回错误了

2023-04-05 04:48 UTC, Stone-afk commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
ctx 超时的情况 第一种情况调用 States 就返回错误，第二种情况， 运行时返回错误

2023-04-05 05:09 UTC, Stone-afk commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
timeout 貌似只能用时间差测，手动关闭的是 canceled， 不过一样的分支就是了

2023-04-05 06:14 UTC, longyue0521 commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
```go
func testTaskPoolStatesCtxTimeout(t *testing.T, pool *OnDemandBlockTaskPool, wantState State) {
	done := make(chan struct{})
        // 你在创建Pool的时候通过指定参数应该就能达到效果，没必要单独写两个pool.Submit
	err := pool.Submit(context.Background(), TaskFunc(func(ctx context.Context) error {
		<-done
		return nil
	}))
	assert.NoError(t, err)
	err = pool.Submit(context.Background(), TaskFunc(func(ctx context.Context) error {
		<-done
		return nil
	}))
	assert.NoError(t, err)

       // 只保留下方循环中的pool.Submit过程就行
	n := cap(pool.queue) - 2
	eg := new(errgroup.Group)

	for i := 0; i < n; i++ {
		eg.Go(func() error {
			return pool.Submit(context.Background(), TaskFunc(func(ctx context.Context) error {
				<-done
				return nil
			}))
		})
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	ch, err := pool.States(ctx, time.Millisecond)
	assert.NoError(t, err)
       // 注意我给的提示顺序：调用States方法，采样一次并记录state，调用cancelCtx
	state1 := <-ch
	assert.Equal(t, wantState, state1)
       // 上面这两句，证明采样协程已经启动，并且采样符合预期
      
        // 执行终止采样操作 
       cancel()
       
       // 断言：采样协程**必须终止**，但极有可能在终止前再采样一次返回用户
       /*
        // 这种方式并不能证明采样协程终止
	state2, ok := <-ch
	if ok {
		assert.Equal(t, wantState, state2)
	} else {
		assert.False(t, ok)
	}
	*/
       for {
               // 当控制流走到这可能恰好拿到最后一次采样
               state2, ok := <-ch
               if !ok {
                    break
               }
               // 拿到就顺带断言验证一下
               assert.Equal(t, wantState, state2)
        }
        // 走到这没报错，没死循环，可以证明采样协程被终止，最后一次拿的采样符合预期
        // 相当于 assert.False(t, ok) 但没必要写
       
        // 先close(done) 让 eg中的协程返回再 assert.NoError(t, eg.Wait())
	_ = eg.Wait()
	close(done)
}
```
学会用 ```go的方式添加语法高亮

2023-04-05 06:23 UTC, Stone-afk commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
要事先提交两次那得执行两次 pool.Submit， 目前没看到其他支持的方法

2023-04-05 06:35 UTC, longyue0521 commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
要事先提交两次的目的是什么？

要达到
> Arrange/Given 协程数 2， 队列容量5， pool处于running状态，提交5个任务，2个运行中，3个等待中；创建可取消的ctx

直接NewPool(2,5)，pool.Submit循环5次，然后pool.Start() 不就行了吗？

2023-04-05 11:47 UTC, longyue0521 commented on pool/task_pool_test.go
> +				c, f := context.WithTimeout(context.Background(), time.Second)
ShutdownNow场景下 验证最终ch关闭就行了

2023-04-05 13:31 UTC, Stone-afk commented
@longyue0521 @flycash

2023-04-05 13:31 UTC, Stone-afk reviewed
mark

2023-04-05 14:02 UTC, flycash submitted a review, later dismissed

2023-04-05 16:05 UTC, longyue0521 requested changes

2023-04-05 16:05 UTC, longyue0521 commented on pool/task_pool_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
这里是因为ctx过期终止的采样协程,不是因为因为shutdown方法,如果用户传入的ctx为background那么采样协程不会终止.

你先把上面的问题都修复吧,这个我来处理吧

2023-04-05 16:17 UTC, Stone-afk commented on pool/task_pool_test.go
> +	assert.Equal(t, wantState.RunningTasksCnt, state1.RunningTasksCnt)
这里有个时间戳，是没有办法提取预设的，所以assert.Equal(t, wantState, state1)行不通

2023-04-05 16:17 UTC, Stone-afk commented on pool/task_pool_test.go
> +		}
这个忘了删掉

2023-04-06 01:39 UTC, longyue0521 commented on pool/task_pool_test.go
> +	assert.Equal(t, wantState.RunningTasksCnt, state1.RunningTasksCnt)
OK

2023-04-06 02:04 UTC, longyue0521 commented
@Stone-afk @flycash 

由测试用例`testTaskPoolStatesPoolShutdown` 可知当前States方法存在无法监听Shutdown信号的问题，即当用户传入context.Background时采样协程无法因ctx超时而退出，另一协程调用pool.Shutdown，那么采样协程不会终止；

### 改进方案一

1. States 方法内添加case <-b.shutdownDone监听Shutdown的信号

2. 在goroutine方法内将下方代码改为

```go
b.shutdownOnce.Do(func() {
	// 状态迁移
	atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
	// 显示通知外部调用者
	b.shutdownDone <- struct{}{}
	close(b.shutdownDone)
})
```

改为

```go
b.shutdownOnce.Do(func() {
	// 状态迁移
	atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
	//  通知内外部信号监听者
	close(b.shutdownDone)
})
```

### 改进方案二

1. 删除b.shutdownDone，引入b.shutdownCtx和shutdownCancel变量与b.shutdownNowCtx和b.shutdownNowCancel保持一致。
2. 在States 方法内添加case <-b.shutdownCtx监听Shutdown的信号
3. 在shutdown和goroutine方法中用b.shutdownCtx和shutdownCancel替换 b.shutdownDone对应的等价操作
    - `close(b.shutdownDone)` => `b.shutdownCancel()`
   - `return b.shutdownDone` => `b.shutdownCtx.Done()` 

做完以上修改后，重新设计测试用例`testTaskPoolStatesPoolShutdown`

2023-04-06 15:57 UTC, Stone-afk commented
这个是我改嘛，不过方案二为啥不直接复用 	shutdownNowCtx   和 shutdownNowCancel 呢

2023-04-06 15:57 UTC, Stone-afk commented
设置两个关闭的 ctx 也太奇怪了

2023-04-06 16:00 UTC, Stone-afk commented
@longyue0521

2023-04-07 02:33 UTC, longyue0521 commented
> 这个是我改嘛，不过方案二为啥不直接复用 shutdownNowCtx 和 shutdownNowCancel 呢

> 设置两个关闭的 ctx 也太奇怪了

shutdownNow和shutdown的调用的时机、流程以及pool所处的状态是不一样的，不能为了省事就复用它，复用后是否会造成其他问题不说，可理解性也会降低——哪些场景会关闭信号，谁会监听信号等就不再是显示知识，而是隐藏在实现细节中的“隐式知识”，这也是之前的为什么用b.shutdownDone某种程度上简化了的shutdownCtx就是想与shutdownNowCtx做区分

在goroutine的Select case 中监听了shutdownNowCtx.Done信号，表示立即中断。而shutdown的语义是优雅关闭，没完成的继续做直到完成，所以不能复用

2023-04-07 02:38 UTC, longyue0521 commented
@Stone-afk 你来改吧，按照方案二改吧

2023-04-07 11:20 UTC, flycash commented
@longyue0521 可以有一个通用的 Shutdown 彻底关闭的信号吗？比如说 Shutdown 和 ShutdownNow 最终都会发出同一个信号。

因为不管怎么来看，在 Shutdown 和 ShutdownNow，也就是不管是优雅退出还是不优雅退出，最终都退出了。那么收到一个一致的信号是比较合理的。

但是我觉得这个地方可以考虑用另外一个合并请求来解决。

2023-04-07 12:42 UTC, longyue0521 commented
> @longyue0521 可以有一个通用的 Shutdown 彻底关闭的信号吗？比如说 Shutdown 和 ShutdownNow 最终都会发出同一个信号。
> 
> 因为不管怎么来看，在 Shutdown 和 ShutdownNow，也就是不管是优雅退出还是不优雅退出，最终都退出了。那么收到一个一致的信号是比较合理的。
> 
> 但是我觉得这个地方可以考虑用另外一个合并请求来解决。

将两者统一为一个信号是完全可以做到的，只是代码可能会更难以理解。先用这个折中的方案让这个PR合并，然后我抽空重构一下。

2023-04-07 13:40 UTC, Stone-afk commented
shutdownCtx  和 shutdowCancel， 是在创建pool的时候复用传进的 ctx， 还是设置两个 ctx 参数

2023-04-07 13:44 UTC, Stone-afk commented
在 goroutine 方法中是不是 直接cancel 就可以了，没必要 return b.shutdownCtx.Done() 吧
```
		b.shutdownOnce.Do(func() {
						// 状态迁移
						atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
						// 显示通知外部调用者
						b.shutdownCancel()
					})
```

b.shutdownOnce.Do 我觉得是不是也没太大必要了b.shutdownOnce就可以删了

2023-04-07 13:44 UTC, Stone-afk reviewed
mark

2023-04-07 13:52 UTC, Stone-afk commented
@longyue0521

2023-04-07 15:59 UTC, longyue0521 commented
> shutdownCtx 和 shutdowCancel， 是在创建pool的时候复用传进的 ctx， 还是设置两个 ctx 参数

参考shutdownNowCtx是如何创建的

2023-04-07 16:08 UTC, longyue0521 commented
> 在 goroutine 方法中是不是 直接cancel 就可以了，没必要 return b.shutdownCtx.Done() 吧

return b.shutdownCtx.Done是用来替换return b.shutdownDone的，在Shutdown方法里，goroutine 方法没有返回值。
你可以先删除shutdownDone字段，然后根据IDE报错进行等价替换。

> 
> ```
> 		b.shutdownOnce.Do(func() {
> 						// 状态迁移
> 						atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
> 						// 显示通知外部调用者
> 						b.shutdownCancel()
> 					})
> ```
> 
> b.shutdownOnce.Do 我觉得是不是也没太大必要了b.shutdownOnce就可以删了

一步一步来吧先完成上面方案二，然后跑一遍测试。等测试都通过了，你再去掉shutdownOnce试试看测试能不能过。不要混在一起搞。

2023-04-07 16:15 UTC, Stone-afk commented
b.shutdownCtx.Done 不应该在 States 方法里面被监听嘛

case <-b.shutdownCtx.Done()

2023-04-07 16:25 UTC, longyue0521 commented
> b.shutdownCtx.Done 不应该在 States 方法里面被监听嘛
> 
> case <-b.shutdownCtx.Done()

应该，你看一下pool.Shutdown的返回值，外部调用者也要监听这个信号。

2023-04-08 04:34 UTC, flycash commented
@longyue0521 我给你写权限了，等这边你觉得没问题了你直接合并进去。用 squash and merge 来合并成一个 commit id。

大体上我觉得这个设计已经符合我的预期了，只差这一个问题了

2023-04-08 08:55 UTC, Stone-afk commented
@longyue0521

2023-04-08 12:37 UTC, longyue0521 commented
@Stone-afk 测试覆盖率不达标，看看下方 codecov/patch 中的提示

2023-04-08 12:37 UTC, longyue0521 commented
> @longyue0521 我给你写权限了，等这边你觉得没问题了你直接合并进去。用 squash and merge 来合并成一个 commit id。
> 
> 大体上我觉得这个设计已经符合我的预期了，只差这一个问题了

好的

2023-04-08 13:46 UTC, longyue0521 requested changes

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool.go
> +	//shutdownDone   chan struct{}
去掉

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool.go
> +					b.shutdownCancel()
这段代码会被多个go协程访问,因为atomic和ctxCancel()都是并发安全的在实现上是没问题的,但是在可理解性上会差一些——读者会觉得多个并发协程都要迁移状态(当然只有一个能成功),多个协程都要发送信号(当然ctxCancel内部实现也处理了重复调用) 改成下面这样呢

```go
// 状态迁移
if atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped) {
         // 显示通知外部调用者
	b.shutdownCancel()
}
```

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool.go
> +			//return b.shutdownDone, nil
去掉

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool.go
> +	}
添加测试用例覆盖

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool.go
> +	}
添加测试用例覆盖

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool_test.go
> +	assert.Nil(t, err)
assert.NoError

2023-04-08 13:46 UTC, longyue0521 commented on pool/task_pool_test.go
> +			State{PoolState: stateStopped, GoCnt: 1, WaitingTasksCnt: 0, QueueSize: 2, RunningTasksCnt: 0})
testTaskPoolStatesPoolShutdownNow内部只断言PoolState,那么最后这个参数就可以不要了,在内部直接断言
```go
assert.Equal(t, stateStopped, state.PoolState)
```

2023-04-08 17:43 UTC, Stone-afk commented on pool/task_pool_test.go
> +			State{PoolState: stateStopped, GoCnt: 1, WaitingTasksCnt: 0, QueueSize: 2, RunningTasksCnt: 0})
@flycash 这里加时间戳是为了上报采样的时间吧，我觉得这里可以不删

2023-04-09 03:27 UTC, longyue0521 commented on pool/task_pool_test.go
> +			State{PoolState: stateStopped, GoCnt: 1, WaitingTasksCnt: 0, QueueSize: 2, RunningTasksCnt: 0})
没懂你什么意思，这里和时间戳有什么关系？

```go
testTaskPoolStatesPoolShutdownNow(t, p,
			State{PoolState: stateStopped, GoCnt: 1, WaitingTasksCnt: 0, QueueSize: 2, RunningTasksCnt: 0})
// 你只对State{PoolState: stateStopped, GoCnt: 1, WaitingTasksCnt: 0, QueueSize: 2, RunningTasksCnt: 0}中的PoolState
// 也就是stateStopped，其他属性WaitingTasksCnt等都没用到
```

2023-04-10 11:11 UTC, Stone-afk commented
@longyue0521 @flycash

2023-04-10 11:19 UTC, longyue0521 approved these changes

2023-04-10 11:33 UTC, merged