retry: Strategy 接口设计与等间隔重试实现
ecodeclub/ekit pull request #169
Opened 2023-03-14 17:01 UTC by chenmingyong0423

retry: Strategy 接口设计与等间隔重试实现
- 创建 Strategy 重试策略接口
- 实现 EqualRetryStrategy 等时间间隔重试策略
- 编写 func (s *EqualRetryStrategy) Next() (time.Duration, bool) 的测试用例

2023-03-15 03:04 UTC, longyue0521 requested changes

2023-03-15 03:04 UTC, longyue0521 commented on retry/retry.go
> +func NewEqualRetryStrategy(maxRetries int, interval time.Duration) *EqualRetryStrategy {
加个error，做个校验处理interval <0 || == 0 情况

2023-03-15 03:04 UTC, longyue0521 commented on retry/retry.go
> +	return s.Interval, false
return time.Duration(0), false

2023-03-15 03:04 UTC, longyue0521 commented on retry/retry.go
> +type EqualRetryStrategy struct {
改为RegularIntervalsRetryStrategy或者RegularRetryStrategy怎么样？定期/常规重试策略

2023-03-15 03:29 UTC, chenmingyong0423 commented on retry/retry_test.go
> +		internal   time.Duration
ok

2023-03-15 03:29 UTC, chenmingyong0423 commented on retry/retry.go
> +func NewEqualRetryStrategy(maxRetries int, interval time.Duration) *EqualRetryStrategy {
好主意

2023-03-15 03:29 UTC, chenmingyong0423 commented on retry/retry.go
> +	return s.Interval, false
ok

2023-03-15 03:31 UTC, chenmingyong0423 commented on retry/retry.go
> +type EqualRetryStrategy struct {
我觉得用 EqualRetryStrategy 更适合描述等间隔重试策略，因为该策略重试的时间间隔是相等的。而 RegularRetryStrategy 可以被用来描述在一定的时间间隔内进行重试的策略，但这种间隔并不一定是相等的，也可以是根据一定规律变化的。对于后面扩展的策略来说，也会包含在里面，例如下一个 issue 就是要实现一个指数退避重试策略，它的间隔时间也是根据一定规律变化的。老哥你觉得呢？

2023-03-15 03:38 UTC, longyue0521 commented on retry/retry.go
> +type EqualRetryStrategy struct {
确实有歧义，就用EqualRetryStrategy吧

2023-03-15 07:44 UTC, flyhigher139 commented on retry/retry.go
> +type EqualRetryStrategy struct {
FixedIntervalRetryStrategy 呢？固定间隔重试策略

2023-03-15 07:56 UTC, chenmingyong0423 commented on retry/retry.go
> +type EqualRetryStrategy struct {
我觉得可以。

2023-03-15 07:57 UTC, longyue0521 commented on retry/retry.go
> +type EqualRetryStrategy struct {
FixedIntervalRetryStrategy确实更精确一些

2023-03-15 09:25 UTC, flycash commented on retry/retry.go
> +	mu         sync.Mutex    // 用于保证并发安全
这个地方，是可以考虑用原子操作取代 mu 的。
在 Next 调用的时候，二话不说直接 cnt := atomic.Add(1)，然后比较 cnt <= maxRetries，就认为可以执行，不然就直接返回 false。

这算是比较典型的先占坑再拉屎的场景了

2023-03-15 09:25 UTC, flycash commented on retry/retry_test.go
> +			name:               "retries = 0, MaxRetries = 3, interval = 1s",
一般来说 name 不是将条件罗列出来。这边应该是初始状态， init case

2023-03-15 09:25 UTC, flycash commented on retry/retry_test.go
> +			name: "retries = 3, MaxRetries = 3, interval = 1s",
这边应该是边缘case，所以本身应该是 retries == MaxRetries, 或者 equals to MaxRetries

2023-03-15 09:25 UTC, flycash commented on retry/retry_test.go
> +			name: "retries = 4, MaxRetries = 3, interval = 1s",
这个是超过重试次数，可以考虑叫做 over MaxRetries

2023-03-15 09:25 UTC, flycash commented on retry/retry_test.go
> +			name: "retries = 0, MaxRetries = 0, interval = 1s",
equals to MaxRetries 0

2023-03-15 09:25 UTC, flycash commented on retry/retry_test.go
> +			name: "retries = 0, MaxRetries = -1, interval = 1s",
negative MaxRetries

2023-03-15 09:37 UTC, chenmingyong0423 commented on retry/retry.go
> +	mu         sync.Mutex    // 用于保证并发安全
好的

2023-03-15 09:37 UTC, chenmingyong0423 commented on retry/retry_test.go
> +			name:               "retries = 0, MaxRetries = 3, interval = 1s",
收到

2023-03-15 09:38 UTC, chenmingyong0423 commented on retry/retry_test.go
> +			name: "retries = 3, MaxRetries = 3, interval = 1s",
收到

2023-03-15 09:38 UTC, chenmingyong0423 commented on retry/retry_test.go
> +			name: "retries = 4, MaxRetries = 3, interval = 1s",
收到

2023-03-15 09:38 UTC, chenmingyong0423 commented on retry/retry_test.go
> +			name: "retries = 0, MaxRetries = 0, interval = 1s",
收到

2023-03-15 09:38 UTC, chenmingyong0423 commented on retry/retry_test.go
> +			name: "retries = 0, MaxRetries = -1, interval = 1s",
收到

2023-03-15 14:35 UTC, longyue0521 requested changes

2023-03-15 14:35 UTC, longyue0521 commented on retry/retry_test.go
>  func TestEqualRetryStrategy_Next(t *testing.T) {
TestFixedIntervalRetryStrategy_Next

2023-03-15 14:35 UTC, longyue0521 commented on retry/retry_test.go
> +func TestNewFixedIntervalRetryStrategy(t *testing.T) {
TestFixedIntervalRetryStrategy_New

2023-03-16 02:22 UTC, flycash approved these changes

2023-03-16 02:23 UTC, merged