feat: 指数退避重试策略实现及单元测试
ecodeclub/ekit pull request #172
Opened 2023-03-16 15:47 UTC by JavHou

feat: 指数退避重试策略实现及单元测试

2023-03-16 16:59 UTC, chenmingyong0423 requested changes

2023-03-16 16:59 UTC, chenmingyong0423 commented on retry/retry.go
> +	beginInterval time.Duration
beginInterval 命名不太正确，建议改成 initialInterval。

2023-03-16 16:59 UTC, chenmingyong0423 commented on retry/retry.go
> +}
New 方法，需要加一个判断，如果初始重试时间大于最大重试时间，返回一个 error

2023-03-16 16:59 UTC, chenmingyong0423 commented on retry/retry.go
> +	interval      time.Duration
我觉得 interval 和 mu 字段可以删掉，在 Next 方法里，你并没有使用 interval 去计算下一次的间隔时间，而是只用于保存新的间隔时间，然后返回给用户，保存这个操作，考虑到并发安全，所以你加了 mu 互斥锁。

新的间隔时间我觉得可以用局部变量去接收，Next 部分逻辑：
- 首先你先使用原子操作去自增重试次数 `retries := atomic.AddInt32(&e.retries, 1)`
- 然后判断是否可以重试，可以的话，再计算重试的间隔时间：`interval := s.initialInterval * time.Duration(math.Pow(2, float64(retries-1)))`

2023-03-16 16:59 UTC, chenmingyong0423 commented on retry/retry.go
> +	return e.maxInterval, false
0, false

2023-03-17 04:54 UTC, longyue0521 requested changes

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry.go
> +	beginInterval time.Duration
这个名字ExponentialInterval容易被理解为”指数区间“，用ExponentialBackoffRetryStrategy是不是更直观一些？

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry.go
> +	return e.maxInterval, false
按照@chenmingyong0423 https://github.com/ecodeclub/ekit/pull/172/files#r1139052925 说的改一下

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry.go
> +}
确实，需要校验一下maxInterval和initialInteral之间关系。

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry_test.go
> +			strategy: &ExponentialIntervalRetryStrategy{
1. 所用name中开头的test去掉，name写的更具描述性一些
2. 把wantStrategy去掉，strategy的类型改为func() *Exxxs的形式，里面用NewExpon....方法来实例化，
3. 把wantInterval 改为 wantIntervals []time.Duration

```go
intervals := []time.Duration
for interval, ok := tc.strategy.Next(); ok; {
    intervals = append(intervals, interval)
}
assert.Equal(t, tc.wantIntervals, intervals)
```

我们应该从用户的角度测试Next的外在表现行为而不是从实现者角度断言重试策略的内部实现状态（重构时会导致测试失败）

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry_test.go
> +			name: "test normal",
去掉test

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry_test.go
> +			name:          "test invalide beginInterval",
invalid initialInterval

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry_test.go
> +			name:          "test invalide maxInterval",
invalid maxInterval

2023-03-17 04:54 UTC, longyue0521 commented on retry/retry_test.go
> +			strategy: &ExponentialIntervalRetryStrategy{
我想了一下@chenmingyong0423 你的TestFixedIntervalRetryStrategy_Next方法中最后断言的部分也应该是上面这种形式。通过收集Next返回的interval的序列来断言Next行为是否符合预期，你当的断言形式只能保证调用一次Next符合预期。

2023-03-17 05:08 UTC, longyue0521 commented on retry/retry_test.go
> +			strategy: &ExponentialIntervalRetryStrategy{
对于无限重试的情况，可以单写一个subtest

2023-03-17 06:17 UTC, chenmingyong0423 commented on retry/retry_test.go
> +			strategy: &ExponentialIntervalRetryStrategy{
> 我想了一下@chenmingyong0423 你的TestFixedIntervalRetryStrategy_Next方法中最后断言的部分也应该是上面这种形式。通过收集Next返回的interval的序列来断言Next行为是否符合预期，你当的断言形式只能保证调用一次Next符合预期。

厉害

2023-03-19 09:56 UTC, JavHou commented on retry/retry_test.go
> +			strategy: &ExponentialIntervalRetryStrategy{
> 我想了一下@chenmingyong0423 你的TestFixedIntervalRetryStrategy_Next方法中最后断言的部分也应该是上面这种形式。通过收集Next返回的interval的序列来断言Next行为是否符合预期，你当的断言形式只能保证调用一次Next符合预期。

ok，新增了每次校验重试后的interval的测试，也新增了对于无限重试的单元测试

2023-03-19 15:04 UTC, longyue0521 requested changes

2023-03-22 02:36 UTC, flycash requested changes

2023-03-22 02:36 UTC, flycash commented on retry/retry.go
> +}
这边不太需要考虑溢出的问题，因为正常用户都不会遇到溢出的问题。我们只需要尽到注意提醒义务就可以了。坦白来说，类似这种安全性的防范，我认为如果一般人都会频繁犯错，我们就校验或者防止；但是如果可以预期一般人都不会犯错，那么我们就可以通过注释这种形态来提醒用户。

因为我们是中文仓库，所以不存在语言壁垒之类的问题。

2023-03-22 02:36 UTC, flycash commented on retry/retry.go
> +		e.interval = e.maxInterval
删掉 interval 这个字段。你每次都用局部变量来计算

2023-03-22 02:36 UTC, flycash commented on retry/retry.go
> +		e.interval = time.Duration(expRetries) * e.initInterval
直接改成：
```go
e.interval = time.Duration(math.Pow(2, float64(retries-1))) * e.initInterval
```

2023-03-22 02:36 UTC, flycash commented on retry/retry.go
> +	if e.maxRetries <= 0 || e.retries <= e.maxRetries {
这个判断放到你前面取出来 retries 之后，因为返回 false 的情况下，是没有必要计算间隔的

2023-03-22 02:36 UTC, flycash commented on retry/retry.go
> +	if e.maxRetries <= 0 || e.retries <= e.maxRetries {
另外不要用 e.retries 来判断，要用 retries 这个局部变量来判断

2023-03-26 10:51 UTC, flycash commented
后面你要是修改好了，再重新打开这个合并请求。

2023-03-26 10:51 UTC, closed without merging