retry: 指数退避重试策略实现
ecodeclub/ekit pull request #173
Opened 2023-04-04 13:27 UTC by richzw

实现任务 https://github.com/ecodeclub/ekit/issues/168

2023-04-04 14:06 UTC, longyue0521 requested changes

2023-04-04 14:06 UTC, longyue0521 commented on retry/backoff.go
> +	}
1. 用atomic.StoreInt64存bo.interval，相应的也该用atomic对应的操作从bo.interval中取
2. bo.maxRetries为什么出现在这个判断中？

2023-04-04 14:06 UTC, longyue0521 commented on retry/backoff.go
> +	}
#168 明确指出**最大重试次数，0 或者负数代表无限制；**（缺少了最大）

2023-04-04 14:08 UTC, longyue0521 commented
@richzw 看一下 https://ekit.gocn.vip/contribution/

2023-04-07 10:44 UTC, flycash requested changes

2023-04-08 04:31 UTC, flycash commented
已经有人实现了，合并进去了。非常感谢

2023-04-08 04:31 UTC, closed without merging