retry: 指数退避重试策略实现
ecodeclub/ekit pull request #174
Opened 2023-04-07 12:23 UTC by chenmingyong0423

retry: 指数退避重试策略实现
- 新增指数退避重试策略（ExponentialBackoffRetryStrategy）
- 编写指数退避策略相关函数和方法的测试用例

2023-04-07 13:29 UTC, longyue0521 requested changes

2023-04-07 13:29 UTC, longyue0521 commented on retry/retry.go
> +		return interval, true
既然考虑到了溢出的问题那就细聊一下。

当interval 再次>0并落在[1, initialInterval）或者[initialInterval , maxInterval）范围内时，你直接返回interval, ture，这就打破了你对外宣称的一旦溢出了就返回maxInterval.

当前实现没法区分interval是第一次落在[initialInterval, maxInterval)还是溢出后（相当于转了一圈后）再次落在该区间的情况。从外部看就会发现interval开始从initialInterval一路增长到maxInterval，稳定在maxInterval一段时间，然后interval再次从更小的值一路增长到initialInterval->maxInterval

所以你需要明确Next语义然后再实现，比如语义是“interval从initialInterval一路增长到maxInterval此后一直稳定在maxInterval”，那么内部一旦检测到一次溢出此后不再计算直接返回maxInterval，或者干脆一旦检测到interval > maxInterval 此后就不再计算直接返回maxInterval

2023-04-07 13:29 UTC, longyue0521 commented on retry/retry_test.go
> +func TestNewExponentialBackoffRetryStrategy(t *testing.T) {
TestExponentialBackoffRetryStrategy_New

2023-04-07 13:29 UTC, longyue0521 commented on retry/retry_test.go
> +	}
```go
n := 100
wantIntervals := make([]time.Duration, 0, n)
....
// 97 -> n - len(wantIntervals)
```
将下方所有100 - > n

2023-04-07 13:29 UTC, longyue0521 commented on retry/retry_test.go
> +	assert.Equal(t, wantIntervals, intervals)
把maxRetries 为0和负数两个场景像下面这样写到单独的子测试中
```go
t.Run("maxRetries 为负数", func() {
     .....
})
```

2023-04-07 13:35 UTC, chenmingyong0423 commented on retry/retry.go
> +		return interval, true
> 既然考虑到了溢出的问题那就细聊一下。
> 
> 当interval 再次>0并落在[1, initialInterval）或者[initialInterval , maxInterval）范围内时，你直接返回interval, ture，这就打破了你对外宣称的一旦溢出了就返回maxInterval.
> 
> 当前实现没法区分interval是第一次落在[initialInterval, maxInterval)还是溢出后（相当于转了一圈后）再次落在该区间的情况。从外部看就会发现interval开始从initialInterval一路增长到maxInterval，稳定在maxInterval一段时间，然后interval再次从更小的值一路增长到initialInterval->maxInterval
> 
> 所以你需要明确Next语义然后再实现，比如语义是“interval从initialInterval一路增长到maxInterval此后一直稳定在maxInterval”，那么内部一旦检测到一次溢出此后不再计算直接返回maxInterval，或者干脆一旦检测到interval > maxInterval 此后就不再计算直接返回maxInterval

呃，不会有转一圈再回来的时候，我测试无限重试的时候，刚开始溢出，interval 的值是负数，后面经过多次计算的时候，interval 的值就变成 0 了，那么 0 乘以任何数都为 0，后面都会一直是 0。

2023-04-07 13:37 UTC, chenmingyong0423 commented on retry/retry.go
> +		return interval, true
> > 既然考虑到了溢出的问题那就细聊一下。
> > 当interval 再次>0并落在[1, initialInterval）或者[initialInterval , maxInterval）范围内时，你直接返回interval, ture，这就打破了你对外宣称的一旦溢出了就返回maxInterval.
> > 当前实现没法区分interval是第一次落在[initialInterval, maxInterval)还是溢出后（相当于转了一圈后）再次落在该区间的情况。从外部看就会发现interval开始从initialInterval一路增长到maxInterval，稳定在maxInterval一段时间，然后interval再次从更小的值一路增长到initialInterval->maxInterval
> > 所以你需要明确Next语义然后再实现，比如语义是“interval从initialInterval一路增长到maxInterval此后一直稳定在maxInterval”，那么内部一旦检测到一次溢出此后不再计算直接返回maxInterval，或者干脆一旦检测到interval > maxInterval 此后就不再计算直接返回maxInterval
> 
> 呃，不会有转一圈再回来的时候，我测试无限重试的时候，刚开始溢出，interval 的值是负数，后面经过多次计算的时候，interval 的值就变成 0 了，那么 0 乘以任何数都为 0，后面都会一直是 0。

所以才会有 interval <= 0 这个条件，刚开始只是<，后面测试发现还有 0 的情况

2023-04-07 13:50 UTC, longyue0521 requested changes

2023-04-07 13:50 UTC, longyue0521 commented on retry/retry_test.go
> +			},
1. name 再具体一点，表达出因达到maxRetries而终止。
2. strategy这种写法使得测试代码与产品代码紧密耦合，对产品代码的调整很容易导致测试代码的修改或者崩溃。

将所有后续测试中所有 strategy := &ExponentialBackoffRetryStrategy{} 替换为New的方式，这里使用下面这种方式
```go
strategy: func () *ExponentialBackoffRetryStrategy {
    // 已经有了对New的测试，那么就选择相信New是没问题的。
   s, err := New(....)
   require.NoError(t, err)
   return s
}
```

2023-04-07 14:09 UTC, chenmingyong0423 commented on retry/retry.go
> +		return interval, true
目前测试是发现：无穷大的时候，计算得到的结果为 0

2023-04-07 14:50 UTC, chenmingyong0423 commented on retry/retry.go
> +		return interval, true
> 干脆一旦检测到interval > maxInterval 此后就不再计算直接返回maxInterval

如果是这样，那结构体是不是应该加一个 flag，检测到 interval > maxInterval 之后，将 flag 置为 true，后续如果是 true，就直接返回 maxInterval

2023-04-07 15:15 UTC, longyue0521 commented on retry/retry.go
> +		return interval, true
我也测试了，虽然retries会转一圈回来，但Go中math.Pow的处理方式没有遵循模运算机制，没法让最终值转一圈回来。interval <= 0的判断是OK的

> > 干脆一旦检测到interval > maxInterval 此后就不再计算直接返回maxInterval
> 
> 如果是这样，那结构体是不是应该加一个 flag，检测到 interval > maxInterval 之后，将 flag 置为 true，后续如果是 true，就直接返回 maxInterval

可以，这样不用每次都计算，能节省CPU时间，注意并发安全。

2023-04-07 15:16 UTC, chenmingyong0423 commented on retry/retry.go
> +		return interval, true
> 

对，确实有并发安全，得加锁，我再想有没有更好的方案，避免加锁。

2023-04-07 15:55 UTC, longyue0521 requested changes

2023-04-07 15:55 UTC, longyue0521 commented on retry/retry_test.go
> +		assert.Equal(t, wantIntervals, intervals)
两个子测试，只有maxRetries的值不同，所以抽取函数达到如下效果：

```go
t.Run("maxRetries equals 0", func(t *testing.T) {
maxRetries = 0
XXXX(maxRetries)
}
t.Run("maxRetries equals -1", func(t *testing.T) {
maxRetries = -1
XXXX(maxRetries)
}
```

2023-04-07 16:09 UTC, longyue0521 approved these changes

2023-04-08 04:30 UTC, flycash approved these changes

2023-04-08 04:30 UTC, merged