mapx: LinkedMap 特性
ecodeclub/ekit pull request #191
Opened 2023-06-05 19:01 UTC by chenmingyong0423

mapx: LinkedMap 特性
- 新增 LinkedMap 结构体
- 为 LinkedMap 实现 mapi 接口的方法
- 为新增方法添加测试方法

2023-06-05 19:07 UTC, chenmingyong0423 commented
golangci-lint / lint (pull_request) 超时了 @flyhigher139

2023-06-06 05:23 UTC, longyue0521 requested changes

2023-06-06 05:23 UTC, longyue0521 commented on mapx/linkedmap.go
> +	}
1. 因为if分支中有return err,下面这个else可以去掉,使代码缩进一列更可读
2. 参考https://github.com/ecodeclub/ekit/blob/dev/list/linked_list.go#L38 及 https://github.com/ecodeclub/ekit/blob/dev/list/linked_list.go#L90 等代码 —— 通过引入dummy节点使得head与tail组成双向循环链表来简化节点插入删除时的边界条件判断

2023-06-06 05:23 UTC, longyue0521 commented on mapx/linkedmap.go
> +	return v, false
var v V 移动到return之上

2023-06-06 05:23 UTC, longyue0521 commented on mapx/linkedmap.go
> +		return lk.value, ok
引入dummy组成双向循环链表后,这里应该两三行就可以了

2023-06-06 05:23 UTC, longyue0521 commented on mapx/linkedmap.go
> +}
在linkedMap中引入一个计数变量,将keys和values改为`make([]XXX, 0, size)`形式

2023-06-06 06:25 UTC, longyue0521 requested changes

2023-06-06 06:25 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +		{
添加测试用例"change value of single key"
1. Act: Put(k1, v1) , Put(k1, v2)
2. Assert: Get(k1) == v2 && Keys() = []{k1} && Values() = []{v2} 
3. 这个用例会触发你代码中的bug, Keys() = []{k1, k1} Values()=[]{v1, v2}
4. 要点:双向循环链表上的节点数要始终与m中key-value对的个数相同

2023-06-07 03:11 UTC, flycash reviewed
@longyue0521 你觉得可以了就直接合并了

2023-06-08 04:12 UTC, longyue0521 requested changes

2023-06-08 04:12 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +func TestLinkedMap_Keys(t *testing.T) {
删除TestLinkedMap_Keys和TestLinkedMap_Values

- 有了TestLinkedMap_Put，TestLinkedMap_Delete，TestLinkedMap_PutAndDelete测试用例的覆盖Keys()和Values()已经作为最终断言在之前测试方法中被测试到了。
- 为了严谨起见，在TestLinkedMap_NewXXXMap中添加对Keys()和Values为[]{}的断言即可。

2023-06-09 10:25 UTC, longyue0521 commented
@chenmingyong0423 

将我之前review时留下的对话作为检查项,先自查一遍你修改后的代码,每确认一个修改就将对应的对话Resolve掉.将所有对话框都Resolve掉后再次发起review request.

2023-06-09 12:41 UTC, chenmingyong0423 commented
> @chenmingyong0423
> 
> 将我之前review时留下的对话作为检查项,先自查一遍你修改后的代码,每确认一个修改就将对应的对话Resolve掉.将所有对话框都Resolve掉后再次发起review request.

关于 error 测试用例那个，上面询问你了，看到回复下哈

2023-06-09 13:09 UTC, longyue0521 commented
> > @chenmingyong0423
> > 将我之前review时留下的对话作为检查项,先自查一遍你修改后的代码,每确认一个修改就将对应的对话Resolve掉.将所有对话框都Resolve掉后再次发起review request.
> 
> 关于 error 测试用例那个，上面询问你了，看到回复下哈
 
我查看了所有对话框，没有找到你的“询问”留言，你是不是没有提交成功？把你询问的对话框截图看看。

2023-06-09 13:50 UTC, chenmingyong0423 commented
> > > @chenmingyong0423
> > > 将我之前review时留下的对话作为检查项,先自查一遍你修改后的代码,每确认一个修改就将对应的对话Resolve掉.将所有对话框都Resolve掉后再次发起review request.
> > 
> > 
> > 关于 error 测试用例那个，上面询问你了，看到回复下哈
> 
> 我查看了所有对话框，没有找到你的“询问”留言，你是不是没有提交成功？把你询问的对话框截图看看。

![image](https://github.com/ecodeclub/ekit/assets/67659676/5e15dd84-4a2d-454c-b2cc-2ee9aac849a8)

2023-06-09 14:00 UTC, longyue0521 commented
> > > > @chenmingyong0423
> > > > 将我之前review时留下的对话作为检查项,先自查一遍你修改后的代码,每确认一个修改就将对应的对话Resolve掉.将所有对话框都Resolve掉后再次发起review request.
> > > 
> > > 
> > > 关于 error 测试用例那个，上面询问你了，看到回复下哈
> > 
> > 
> > 我查看了所有对话框，没有找到你的“询问”留言，你是不是没有提交成功？把你询问的对话框截图看看。
> 
> ![image](https://user-images.githubusercontent.com/67659676/244711002-5e15dd84-4a2d-454c-b2cc-2ee9aac849a8.png)

图片中你头像右侧有pending字样证明你的评论未提交，你提交以下，我们在对应位置讨论，留下讨论轨迹。

2023-06-09 14:02 UTC, longyue0521 requested changes

2023-06-09 14:21 UTC, chenmingyong0423 commented on mapx/linkedmap_test.go
> +		},
我的意思是就是当前只有两种实现，hashmap 和 treemap，hashmap 底层代码没有返回 error 的情况，treemap 很难测试出 error。

2023-06-09 15:10 UTC, chenmingyong0423 commented on mapx/linkedmap_test.go
> +		},
明白，当前两种实现无法通过 error 的测试用例，所以我需要创建一个 `fakeMap` 吧

2023-06-10 01:17 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +		},
是的

2023-06-11 05:19 UTC, longyue0521 requested changes

2023-06-11 05:19 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +			name: "put k1 → delete k1 → put k2",
删掉这两个测试用例，因为下方已经有了`put k1 → delete k1 → put k2 → put k3`

2023-06-11 05:46 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +}
fakemap还有一种简单的实现方式

```go
type fakeMap[K any, V any] struct {
   *LinkedMap[K, V]
   count          int
   activeFirstErr bool
}
// 只需要重新实现Put逻辑，其他逻辑不需要实现，会自动委派给内嵌的*LinkedMap[K, V]
func (f *fakeMap[K, V]) Put(key K, val V) error {
     // 根据需求返回error
     // .......
     return f.LinkedMap.Put(key, val)
}
```

2023-06-12 04:37 UTC, longyue0521 requested changes

2023-06-12 04:37 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +		fakeMap   func(t *testing.T) *fakeMap[int, int]
将这个fakeMap去掉

2023-06-12 04:37 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +			},
在构造linkedMap的时候，将fakeMap作为linkedMap中的m传入。

2023-06-12 04:37 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +			},
同上

2023-06-12 04:37 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +			}
我们测试目标是linkedMap，所以断言就应该在linkedMap上，至于linkedMap中那个m具体是”指向“fakeMap还是其他mapi实现我们并不关心。

所以你可以将`newFakeMap[K comparable, V any](activeFirstErr bool, comparator ekit.Comparator[K]) (*fakeMap[K, V], error)` 改为`newLinkedFakeMap[xxx](yyy) ( *LinkedMap[xxx], error)`它与`NewLinkedTreeMap`和`NewLinkedHashMap`处于同等地位，都是用来构造测试目标linkedMap，只不过各自内部的m”指向“了不同的mapi实现。

2023-06-12 04:37 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +			}
在你完成本次修改后，在本地运行一下该测试用例集合，看看linkedmap.go中70-71行是否被覆盖。一般来说完成上述修改后覆盖率应该是100%

2023-06-12 04:38 UTC, longyue0521 commented on mapx/linkedmap_test.go
> +// 只需要重新实现Put逻辑，其他逻辑不需要实现，会自动委派给内嵌的*LinkedMap[K, V]
这个注释去掉，在你用fakeMap构造linkedMap时，如果fakeMap没有实现mapi接口是无法传递给linkedMap.m的，能传递也就间接验证了这句话。

2023-06-12 14:43 UTC, longyue0521 submitted a review, later dismissed

2023-06-12 14:48 UTC, merged