syncx: sync.Cond的超时等待版，Cond.WaitWithContext(ctx)
ecodeclub/ekit pull request #192
Opened 2023-06-12 08:41 UTC by fifth-month

整体思路是每一个等待的对象都创建一个chan，然后监听chan和ctx的信号；被通知时，如果先进入了超时分支，但同时被signal通知时，会随机选择一个，但是被signal通知也就意味着成功了，只是同时超时了而已，所以超时后需要先加锁，然后再判断是否被通知过，如果被通知过，就直接返回，否则进入超时的真正流程，移除等待的对象。

2023-06-12 09:14 UTC, longyue0521 commented
@fifth-month 根据 https://ekit.gocn.vip/contribution/ 修一下下面的错误

2023-06-12 13:12 UTC, flycash reviewed
总体上来说，这就是之前我说的一个等待者一个 chan 的实现，类似于 sql.DB 这种连接池的设计。核心缺陷就是如果等待者很多，这里会创建很多 chan，倒也可以接受。

@longyue0521 请帮忙看看这边的并发问题。

2023-06-12 13:12 UTC, flycash commented on syncx/cond.go
> +		return nil
在这两个返回 nil 的地方，你需要将它从 nofifyList 里面挪走吧？

2023-06-12 13:12 UTC, flycash commented on syncx/cond.go
> +	close(n.ch)
看上去你这里是一个等待者对应于一个 chan，那么这里可以使用 n.ch <- struct 来发送信号吗？

如果可以的话，那么整个 notifyItem 其实都是可以复用的，就可以使用 sync.Pool 来优化

2023-06-12 13:12 UTC, flycash commented on syncx/cond_test.go
> +		<-awake // Will deadlock if no goroutine wakes up
同时要进一步检查 c 内部的数据结构，比如说这个时候可以预期已经少了一个等待者，那么应该还剩下 n-1 个等待者。这个检测能够确保你维护内部结构的时候没有出错。

2023-06-12 13:12 UTC, flycash commented on syncx/cond_test.go
> +		c.Broadcast()
同样在 Broadcast 之后，你一样要检测内部结构。

这些单元测试的核心问题在于，你没有确认谁被唤醒了。而这个在你的实现里面是可以预期的，也就是永远都是队首的那个被唤醒。所以你可以进一步试着检测一下确实是某一个特定的对象被唤醒了。

2023-06-12 13:34 UTC, fifth-month commented on syncx/cond.go
> +		return nil
超时返回的时候，调用了移除这个对象的方法，而正常被唤醒的情况是signalOne和Broadcast的方法里面就已经移除了这个对象

2023-06-12 13:38 UTC, fifth-month commented on syncx/cond.go
> +	close(n.ch)
理论上可以通过把notifyItem这个对象整个直接嵌入在notifyList里面，直接使用chan对象，不再包一层struct，这样可以节约notifyItem上两个指针的开销，但是chan的创建开销应该没法省，额外的list上的element开销可能可以用sync.Pool省下来

2023-06-12 14:57 UTC, longyue0521 requested changes

2023-06-12 15:43 UTC, fifth-month commented on syncx/cond.go
> +}
我再改改结构，让它看起来合理点

2023-06-13 03:31 UTC, longyue0521 commented on syncx/cond.go
> +		return nil
”在超时的时候并不代表真正的超时“其实是你认为Singnal和Broadcast产生的”信号“比ctx.Done产生的信号的“信号”优先级要高，即便先产生了超时信号signal或者broadcast信号也会掩盖/吞掉超时信号

我想和你讨论的是从用户角度看cond.WaitWithContext(ctx)的逻辑语义，用户在使用时能够做哪些假设？err表示什么？是否能尽可能准确地返回超时信号？返回后我是要手动检查ctx.Err()还是直接根据返回的err来判断是超时返回还是被唤醒返回？

有了上述的逻辑语义（Spec）才有讨论实现细节的基础。

2023-06-13 03:41 UTC, fifth-month commented
整体上移除了notifyItem的结构，方法打散在了notifyList中。修改了部分测试，增加验证了超时控制的情况下唤醒的有序性

2023-06-13 03:55 UTC, fifth-month commented on syncx/cond.go
> +		return nil
可以换个角度想，其实已经通知要唤醒你了，但是由于goroutine调度的机制，导致延迟，结果时间也刚好到了，理论上这个可以算成功，而不能算超时，因为你说1s，那刚好1s为什么不能算成功

2023-06-13 03:59 UTC, longyue0521 commented on syncx/cond.go
> +		return nil
假设已经实现了，你现在需要注释cond.WaitWithContext(ctx) error方法，像标准库中的cond一样给出使用说明

2023-06-13 04:03 UTC, fifth-month commented on syncx/cond.go
> +		return nil
如果非要纠结这个的话，golang.org/x/sync/semaphore 包里面的func (s *Weighted) Acquire(ctx context.Context, n int64) error 它的超时语义也是有问题，因为实现是一样的

2023-06-13 04:05 UTC, fifth-month commented on syncx/cond.go
> +		return nil
当然，你说有道理，只是因为技术实现比较麻烦，所以选择当做看不见超时而已，使用方是感觉不太出来的

2023-06-13 04:08 UTC, fifth-month commented on syncx/cond.go
> +		return nil
那我把使用说明都加上

2023-06-13 04:36 UTC, fifth-month commented
方法的使用注释加好了，基本上参考了sync.Cond的注释

2023-06-13 12:34 UTC, flycash commented on syncx/cond.go
> +	close(n.ch)
不是，我的意思是这里可以不用 close(n.ch) 这种做法来唤醒，而是直接发送一个 n.ch <- struct。这里和我之前跟你们讲的是不太一样的，之前那个是因为我们不清楚有几个人等信号。但是这里是很明确的，每一个人过来调用 Wait 的时候，你都会创建一个 chan。我的意思是，既然都是一对一了，那么自然可以考虑直接发一个信号。而发信号之后，ch 本身没被关闭，那么就还可以继续被复用。

2023-06-13 12:36 UTC, flycash reviewed
虽然有点坑，但是我还想说，换成中文写注释，因为我这个首要考虑我们中国人能读懂。翻译软件那么发达，老外自己想用就自己翻译。而且……正常来说中国人的开源项目比较难得到老外的认可，所以不需要考虑英文。你看我们的文档、注释和错误信息全部都是中文……

2023-06-13 12:45 UTC, flycash commented
@fifth-month 我暂时关了这个合并请求，你在企业微信或者邮箱给我发一个邮件，我有点小问题问你一下=。=不好意思了

2023-06-14 03:03 UTC, fifth-month commented
把方法使用注释改成了中文，将WaitWithContext和Wait合并成了Wait(ctx)方法，优化了channel的使用逻辑，使用发送消息，代替关闭channel来做通知，同时由于不再使用关闭channel来通知，使得channel能够被复用，所以加入了sync.Pool优化channel的创建问题，benchmark测试内存分配降低了一半。但是还有一些内存分配主要集中在list的Element的分配上，但这个官方库没有办法复用list.Element，可能得自己写一个双链表才可以解决这个问题。

2023-06-14 04:00 UTC, longyue0521 commented
@fifth-month @flycash 

我一直在强调并确认`wait(ctx) error`的逻辑语义，这是因为`wait(ctx) error`的后置条件（可以依赖的假设）对用户的使用体验有很大影响。

场景分析：
1. 当调用者协程因超时返回，且中途没有被notify，wait(ctx) !=nil && ctx.Err() != nil
2. 当调用者协程因notify返回，且中途没有超时，wait(ctx) == nil && ctx.Err() == nil
3. 当调用者协程因超时返回，返回途中被notify或者两个信号同时出现因select的随机性选择了超时分支，wait(ctx) == ? && ctx.Err() != nil
4. 当调用者协程因notify返回，返回途中超时或者两个信号同时出现因select的随机性选择了notify分支， wait(ctx) == ? && ctx.Err() != nil

当前实现在场景3和4中对外的逻辑语义是`wait(ctx) == nil && ctx.Err() != nil`，作为一个对超时敏感的用户我就很困惑，场景1逻辑语义`wait(ctx) !=nil && ctx.Err() != nil` 两者返回值相匹配，代码会走入超时逻辑分支`if err := wait(ctx); err != nil {`，而场景3和4的逻辑语义是`wait(ctx) == nil && ctx.Err() != nil`两者返回值不匹配，如果我想进入超时逻辑分支我必须`if err := wait(ctx); err != nil || ctx.Err() != nil {`。接着就出现了`_ := wait(ctx); if ctx.Err() != nil { ....}`

那么wait(ctx)的返回值到底表示什么？为什么是error类型。

我认为`wait(ctx)`的返回值表示的是”信号“出现的情况——仅超时信号，仅唤醒信号或协程从wait返回时最终的状态（两个信号都存在）
使用error类型返回值会像上面举例那样”误导“用户，不如限定`wait(ctx) (bool)`表示是否被唤醒，超时信号由ctx.Err承担，用户想控制超时自己写`if ctx.Err() != nil {`，当两个信号同时出现时`wait(ctx) == true && ctx.Err() != nil`，用户可以在两个信号之间自主选择是超时还是继续。

2023-06-14 04:16 UTC, fifth-month commented
你说的意思，我懂，语义的问题确实是存在的，但是我个人觉得这个调度机制本身就没办法去保证一定是实时的问题，就算你
select { 
case <- ctx.Done:
   // 超时了 
default:
  // 没有超时，但是真的没有超时吗
  // 也许刚进入default分支就发生协程切换了，
  <--  这里发生了协程切换
  // 切换回来再执行的时候难道再检查一次有没有超时？
}
我个人认为，本身go就不能太精准的控制时间问题，特别是在多线程的情况下
如果我们相信就绪状态的goroutine会很快就被调度执行的话，我们就不用太在意是否恰好超时的问题

2023-06-14 04:34 UTC, fifth-month commented
不过你说的返回bool确实感觉会更合理点，我觉得这里Wait(ctx) bool返回true代表条件有了变化被唤醒，false代表条件没有变化被唤醒（也就是超时而唤醒的）。

2023-06-14 04:45 UTC, flycash commented
其实我还是倾向于保持和其它超时控制一样的语义。就是使用 error。

在正常的使用场景下，我认为大部分用户不会特别关心是什么错误：
```go
if wait(ctx) != nil {
    return //
}
```

如果要进一步深入下去， if wait(ctx) == context.DeadlineExceed;  就是超时；而 wait(ctx)==context.Cancel 就是被取消了。这个语义是非常清楚的。如果是 bool 的话是分辨不出来这两种情况的。

关于时机的问题，也就是如果要是超时和唤醒同时发生，我觉得这里倒是没必要仔细去分辨。比如说我们在sql.DB 里面也有类似的问题，即获取链接和超时同时发生。他们实际上就是，你进去了 select 哪个分支，就认为是哪个情况。

<img width="946" alt="image" src="https://github.com/ecodeclub/ekit/assets/9923838/bc6d3d44-756c-42f6-9591-0f4e68789ee8">


我们这里在超时之后，如果刚好也收到了信号，能不能唤醒下一个人（比如在上图，他们是把连接放回去了）？这样就是永远保证，在超时的时候返回 ctx.Err。这样比较贴近已有的做法。

2023-06-15 10:56 UTC, longyue0521 commented
> 其实我还是倾向于保持和其它超时控制一样的语义。就是使用 error。
> 
> 在正常的使用场景下，我认为大部分用户不会特别关心是什么错误：
> 
> ```go
> if wait(ctx) != nil {
>     return //
> }
> ```
> 
> 如果要进一步深入下去， if wait(ctx) == context.DeadlineExceed; 就是超时；而 wait(ctx)==context.Cancel 就是被取消了。这个语义是非常清楚的。如果是 bool 的话是分辨不出来这两种情况的。
> 
> 关于时机的问题，也就是如果要是超时和唤醒同时发生，我觉得这里倒是没必要仔细去分辨。比如说我们在sql.DB 里面也有类似的问题，即获取链接和超时同时发生。他们实际上就是，你进去了 select 哪个分支，就认为是哪个情况。
> 
> <img alt="image" width="946" src="https://user-images.githubusercontent.com/9923838/245677631-bc6d3d44-756c-42f6-9591-0f4e68789ee8.png">
> 我们这里在超时之后，如果刚好也收到了信号，能不能唤醒下一个人（比如在上图，他们是把连接放回去了）？这样就是永远保证，在超时的时候返回 ctx.Err。这样比较贴近已有的做法。

@fifth-month 按照这个语义调整一下你的代码。

2023-06-15 11:40 UTC, fifth-month commented
调整好了，现在是超时收到正常信号，会传递给下一个队首.

2023-06-15 15:13 UTC, longyue0521 requested changes

2023-06-15 15:13 UTC, longyue0521 commented on syncx/cond_test.go
> +func TestCond_WakeOrder(t *testing.T) {
TestCond_Signal

2023-06-15 15:17 UTC, longyue0521 commented
@fifth-month 每修改一处后点击resolve conversion将相应对话框关闭。

2023-06-16 01:23 UTC, fifth-month commented on syncx/cond.go
> +func (l *notifyList) waitWithContext(ctx context.Context, elem *list.Element) error {
这是一个纠结的地方，因为要实现可复用的doubly linked list，那这个doubly linked list放在这个包里面吗？因为感觉是这个也是通用的数据结构

2023-06-16 02:48 UTC, longyue0521 commented on syncx/cond.go
> +func (l *notifyList) waitWithContext(ctx context.Context, elem *list.Element) error {
通用的已经有了在list包下是泛型的，这里是定制的（裁剪的，不用实现全部方法）+sync.Pool优化的，类比于mapx目录下的LinkedMap实现（可以去看看）

2023-06-24 05:59 UTC, longyue0521 commented
@fifth-month 你还准备继续这个PR吗？

2023-06-25 06:13 UTC, fifth-month commented
应该不急吧，还得等几天

2023-06-27 14:45 UTC, fifth-month commented on syncx/cond.go
> +			l.notifyNext()
改了

2023-06-27 14:46 UTC, fifth-month commented on syncx/cond.go
> +// 绝大多数简单用例, 最好使用channels而不是 Cond
channels 是官方说法，这句不变，第2条调整了一下，基本都是维护官方的翻译

2023-06-27 14:49 UTC, fifth-month commented
本来是想实现一个简版的linkedlist，然后配合notifyList使用，但是发现链表元素在移除的时候回收和channel的回收不同步进行，会导致死锁，索性干脆把chan直接挪入linkedlist的实现里面改成了chanList的一个特定实现，只为了这个模块而存在的一个channel的双链表。

2023-06-27 14:53 UTC, fifth-month commented on syncx/cond.go
> +// # Cond 在初次使用后，不要复制对象
复制检查代码比较复杂，只好增加了noCopy这个结构体为静态代码检查增加了点方便

2023-06-29 05:12 UTC, longyue0521 requested changes

2023-06-29 05:12 UTC, longyue0521 commented on syncx/cond.go
> +	case <-ctx.Done(): // 进了超时分支，但同时协程发生了切换进入了notifyOne的分支；这个时候，根据remove的成功与否可以知道是否是需要唤醒的
这行注释过期了

2023-06-29 05:12 UTC, longyue0521 commented on syncx/cond.go
> +			// 这种情况代表加锁成功后，没有被通知到，属于真正的超时的情况，从队列移除等待对象，避免被错误通知唤醒，返回超时错误信息
这行注释过期了, 去掉“，返回超时错误信息”

重新审查所有注释,使其与当前代码实现一致

2023-07-17 02:18 UTC, fifth-month commented on syncx/cond.go
> +func (*noCopy) Unlock() {}
增加了拷贝检测

2023-07-17 02:21 UTC, fifth-month commented
增加了运行时拷贝检测，修正了初始化体验，尽可能保证初始化使用方式和官方Cond一致（支持syncx.Cond{L:sync.Locker}）

2023-08-10 14:49 UTC, merged