syncx: 支持分key加锁#224
ecodeclub/ekit pull request #225
Opened 2023-10-08 07:51 UTC by WeiJiadong

2023-10-08 08:54 UTC, junwense commented
hash冲突了能解决么

2023-10-08 11:53 UTC, flycash commented
哈希冲突了无所谓，也就是多个 key 共用一个锁而已。但是相比全局一个锁，并发的竞争激烈程度是下降了的

2023-10-08 11:54 UTC, flycash commented on syncx/segment_key_lock.go
> +	lock := &s.locks[hash%uint32(len(s.locks))]
我的理解是不用取地址，本身不会触发复制吧？

2023-10-08 11:57 UTC, WeiJiadong commented on syncx/segment_key_lock.go
> +	lock := &s.locks[hash%uint32(len(s.locks))]
主要有提示，比如go vet，不想破坏锁不能复制的语义

2023-10-08 11:58 UTC, WeiJiadong commented
> hash冲突了能解决么

不能，但冲突也不影响。现在尽量做的是让它更均匀，尽量避免冲突，冲突时，lock会阻塞。

2023-10-08 12:01 UTC, flycash requested changes

2023-10-08 12:01 UTC, flycash commented on syncx/segment_key_lock_test.go
> +	time.Sleep(50 * time.Millisecond)
sleep 会造成测试不稳定。你可以考虑在 s.Lock 成功之后，发送一个东西到一个 channel。然后这里就是从 channel 里面读取数据，进行下一步。

2023-10-08 12:01 UTC, flycash commented on syncx/segment_key_lock_test.go
> +		t.Log("Read operation executed")
你也可以同样用 channel 来发送数据。

2023-10-08 12:01 UTC, flycash commented on syncx/segment_key_lock_test.go
> +	wg.Wait()
只要你这里收到了发出来的数据，就可以断行你的测试是成功了的。

2023-10-08 12:39 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +func TestSegmentKeysLock(t *testing.T) {
已修改成断言方式来check

2023-10-08 12:41 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +	wg.Wait()
是的，修改了，使用断言以及cond来做

2023-10-08 12:42 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +		t.Log("Read operation executed")
修改了，使用断言+cond来做次序以及数据自动check

2023-10-08 12:56 UTC, flycash commented on syncx/segment_key_lock.go
> +	lock := &s.locks[hash%uint32(len(s.locks))]
如果这样的话，直接维持住指针。而后在 New 的时候就直接搞出来指针。相当于把这里取地址的性能开销，挪过去了最开始的初始化的时候。

2023-10-09 02:50 UTC, junwense commented
> 哈希冲突了无所谓，也就是多个 key 共用一个锁而已。但是相比全局一个锁，并发的竞争激烈程度是下降了的

如果锁的数量不多，并且业务允许，这个确实挺好的，这样也不用考虑锁回收和并发的问题，我开始想的是把锁的获取封装起来，对锁的获取提供不同的支持，比如hash是否允许冲突，以及底层数据结构的实现，不过这样并发问题又得考虑

2023-10-09 03:10 UTC, longyue0521 commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
另外这个测试用例有些复杂且意图有些不清晰, 是不是可以这样:
1. hash值相同的key,验证并发读写、读读、写写,只要验证有竞争即可
```go
// 核心伪代码
data = ""

// 启动多个个写协程
for ... {
go func () {
      s.Lock(Key)
      data = "1"
      s.UnLock(Key)
}
}
// 启动1个读协程
go func () {
      s.RLock(Key)
      ch <-data
      s.RUnLock(Key)
}

assert.Equal(t, "1", <-ch)
```
3. hash值不同的key, 相互不竞争
```go
// 核心伪代码
data1= ""
data2= ""

go func () {
    defer wg.Done()
      s.Lock(Key1)
      data1 = "1"
      s.UnLock(Key)
}
// 启动1个读协程
go func () {
    defer wg.Done()
      s.Lock(Key2)
      data2 = "2"
      s.UnLock(Key)
}
wg.Wait()
assert.Equal(t, "1", data1)
assert.Equal(t, "2", data2)
```

2023-10-09 07:12 UTC, WeiJiadong commented on syncx/segment_key_lock.go
> +	lock := &s.locks[hash%uint32(len(s.locks))]
已改

2023-10-09 07:12 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +	time.Sleep(50 * time.Millisecond)
修改了，使用断言+cond来做次序以及数据自动check

2023-10-09 07:27 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
> go 1.21中有atomic.Bool可以看一下,语义更准确
这里也可以写别的值，主要是验证是否写了后能被读到。
另外，如果用atomic.Bool这个特性，会对使用者版本有要求，要升级才能支持，不然编译不过。

2023-10-09 07:54 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
> 另外这个测试用例有些复杂且意图有些不清晰, 是不是可以这样:
> 
> 1. hash值相同的key,验证并发读写、读读、写写,只要验证有竞争即可
> 
> ```go
> // 核心伪代码
> // 真实竞争数据
> data = ""
> 
> // 启动多个个写协程
> for ... {
> go func () {
>       s.Lock(Key)
>       data = "1"
>       s.UnLock(Key)
> }
> }
> // 启动1个读协程, 多个写与一个读竞争大概率写赢,读到写后的新数据
> go func () {
>       s.RLock(Key)
>       ch <-data
>       s.RUnLock(Key)
> }
> 
> assert.Equal(t, "1", <-ch)
> ```
> 
> 3. hash值不同的key, 相互竞争不受控制, 这个不好写可以不写
> 
> ```go
> // 真实竞争数据
> data= ""
> 
> 
> // 对key1数据写
> go func () {
>       s.Lock(Key1)
>       data = "1"
>       s.UnLock(Key1)
> }
> // 对key2数据写
> go func () {
>       s.Lock(Key2)
>       data = "2"
>       s.UnLock(Key2)
> }
> // 检测到竞争
> ```

确实，理论上是应该这么验证，不仅需要覆盖代码，还需要验证读写锁的特性。
我补一下关于读写锁特性的验证。

2023-10-09 08:17 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
思考了下，似乎不借助time.Sleep之类的，写写互斥的测试用例不好写，会卡死测试进程。

2023-10-09 08:53 UTC, longyue0521 commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
其实最后那个s.Lock(Key1)与 s.Lock(Key2),是想用一个反例来验证底层,对于两个hash值不同的key使用的是两把读写锁,而不是同一把锁, 验证的方式就是运行测试的时候加-race参数会报错 —— data还是被两个写, 或读写竞争访问了, 但这样的“测试”没法编写.所以只能通过review来确保,不同hash值的key使用的是两把读写锁.

2023-10-09 08:57 UTC, longyue0521 commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
> > go 1.21中有atomic.Bool可以看一下,语义更准确
> > 这里也可以写别的值，主要是验证是否写了后能被读到。
> > 另外，如果用atomic.Bool这个特性，会对使用者版本有要求，要升级才能支持，不然编译不过。

我写错了 go1.19中就支持了[atomic.Bool](https://pkg.go.dev/sync/atomic#Bool), ekit要求1.20完全可以用

2023-10-09 12:35 UTC, flycash commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
@longyue0521 确认没问题你就直接合并了。

2023-10-10 00:44 UTC, longyue0521 commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
@flycash  好的

2023-10-10 06:30 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +	var readStarted int32
> > > go 1.21中有atomic.Bool可以看一下,语义更准确
> > > 这里也可以写别的值，主要是验证是否写了后能被读到。
> > > 另外，如果用atomic.Bool这个特性，会对使用者版本有要求，要升级才能支持，不然编译不过。
> 
> 我写错了 go1.19中就支持了[atomic.Bool](https://pkg.go.dev/sync/atomic#Bool), ekit要求1.20完全可以用

已修改成atomic.Bool，以及补齐了用例注释说明

2023-10-10 09:50 UTC, longyue0521 requested changes

2023-10-10 10:33 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +
我认为当前用例是没问题的，我觉得你没明白这段测试代码的意图。
针对提出的这几个点以及你给的用例思路，有这几个点：
1.并不等效。我是想模拟的是写锁能将共享区数据正确同步给读者。
2.sleep不是稳定的，flycash也有提到。所以这里用到了多个共享手段来尽力模拟多协程场景的协作。
3.具体的用法展示也说明了。写的时候加写锁，读的时候加读锁。
4.是否需要更多的协程？我认为是不需要的，因为我们需要验证的是第1点的效果，即写能正确写，读能正确读。

2023-10-10 15:36 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +
那我明白你的问题了，可能你没有理解到锁的本质。
go的多协程编程不止是锁，还有chan，它的核心是两个：
1.数据可见性      --就是这个用例在验证的
2.数据访问串行

其实这俩特性都是同一个锁才能满足。2的验证会有阻塞，不太好写，但其实验证1就足够了。

2023-10-10 15:38 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +
其实它的本质是内存屏障。

2023-10-11 02:44 UTC, WeiJiadong commented on syncx/segment_key_lock_test.go
> +
关于可见性，我写一个操作系统经典的pv模型示例（没上述的共享手段，数据值val可见性就会有问题）：
```
package main

import (
	"fmt"
	"sync"
)

func p(val *int) {
	(*val)--
	for *val < 0 {
	}
}

func v(val *int) {
	(*val)++
}

func consumer(cVal *int, pVal *int) {
	for {
		p(cVal)
		fmt.Println("consumer is running...")
		v(pVal)
	}
}

func productor(cVal *int, pVal *int) {
	for {
		p(pVal)
		fmt.Println("productor is running...")
		v(cVal)
	}
}

func main() {
	var p int = 1
	var c int = 0

	go productor(&c, &p)
	go consumer(&c, &p)

	var m sync.Mutex
	m.Lock()
	m.Lock()

	return
}
```
有个概念一定要搞清：串行访问 != 多协程并发没问题。**因为你的数据改变要正确同步给其他协程才行**。
回到当前的问题，目前是验证了锁的特性之一，而目前场景显而易见锁的特性不会被分割，所以只要验证其中一个特性没问题，就可以说明没问题。

2023-10-12 02:35 UTC, longyue0521 requested changes

2023-10-13 08:40 UTC, flycash approved these changes
我先合并了。这里面确实不好测试，我引入 TryXXX 的 API 来测试

2023-10-13 08:44 UTC, merged