list中增加了skip list, map中添加了UpdateMap方法
ecodeclub/ekit pull request #231
Opened 2023-10-16 05:30 UTC by AIJoe1995

list中增加了skip list, map中添加了UpdateMap方法

2023-10-16 06:23 UTC, longyue0521 commented
@AIJoe1995 参考已合并PR, 修复一下下方检查列表中的问题,问题描述详见检查项后方的Details.

2023-10-16 06:37 UTC, longyue0521 requested changes

2023-10-16 06:37 UTC, longyue0521 commented on mapx/map.go
> +func UpdateMap[K comparable, V any](m1, m2 map[K]V) map[K]V {
添加这个UpdateMap的目的是什么, 有哪个关联的issue吗?

2023-10-16 06:37 UTC, longyue0521 commented on mapx/map_test.go
> +			name:    "update map",
缺少如下用例:
1. m1为空, m2不为空
2. m1不为空,m2为空
3. m1、m2均不为空
    - m1和m2中Key完全相同
    - m1和m2中Key部分相同
        -  m1的全部key与m2中的部分Key相同 (你写的相当于这个测试用例)
            -  单个key相同
            -  多个key相同
        - m1的部分key与m2中的部分key相同
            -  单个key相同
            -  多个key相同
        -  m2的全部key与m1中的部分Key相同
            -  单个key相同
            -  多个key相同
        - m2的部分key与m1中的部分key相同
            -  单个key相同
            -  多个key相同

2023-10-16 08:07 UTC, flyhigher139 commented
我也写过一个跳表的实现，虽说大差不差，不过我觉得也可以借鉴一下有些写法或封装：

https://github.com/igevin/algokit/blob/master/collection/skiplist/skiplist.go

2023-10-16 08:08 UTC, flycash reviewed
@juniaoshaonian 请帮助 review 这个合并请求，我记得之前你好像写过一个跳表。

2023-10-16 08:08 UTC, flycash commented on list/skip_list.go
> +type SkipList[T any] struct {
skiplist 你丢过去 internal 里面。然后在这里暴露出来，并且 skiplist 需要实现我们的 list 接口。

2023-10-16 08:08 UTC, flycash commented on mapx/map.go
> +func UpdateMap[K comparable, V any](m1, m2 map[K]V) map[K]V {
暂时用不太上，可以删除掉。这个语义在别的语言里面应该是叫做 Copy 或者 Assign

2023-10-16 08:18 UTC, flycash reviewed
先丢过去 Internal，然后在这里暴露，实现 List 接口。在实现 List 接口之后，不要急于添加方法，可以等后面有需要的时候再加。

2023-10-16 08:18 UTC, flycash commented on list/skip_list.go
> +func SkipListToSlice[T any](sl *SkipList[T]) []T {
在 List 接口里面就有一个 ToSlice 的方法，你应该定义在 sl 上的。

2023-10-16 08:18 UTC, flycash commented on list/skip_list.go
> +// update[i] contains a pointer to the left of the location of the insertion/deletion for level i
英文的就不要留着了。还有，你这个该不会抄的吧？

2023-10-16 08:18 UTC, flycash commented on list/skip_list.go
> +// update[i] contains a pointer to the left of the location of the insertion/deletion for level i
用中文来写

2023-10-16 09:22 UTC, flycash commented
> 我也写过一个跳表的实现，虽说大差不差，不过我觉得也可以借鉴一下有些写法或封装：
> 
> https://github.com/igevin/algokit/blob/master/collection/skiplist/skiplist.go

帮着 review，我已经好久没写过了，人已经是一个废物了

2023-10-16 09:31 UTC, AIJoe1995 commented on list/skip_list.go
> +// update[i] contains a pointer to the left of the location of the insertion/deletion for level i
我找了网上的跳表实现 是按这个写的 https://leeyzero.github.io/2022/11/24/understanding-skip-list/
英文主要是从论文里copy过来的，Skip lists: a probabilistic alternative to balanced trees, 想要帮助理解实现，我改成中文写。

2023-10-16 09:33 UTC, AIJoe1995 commented on mapx/map_test.go
> +			name:    "update map",
谢谢~

2023-10-16 10:48 UTC, AIJoe1995 commented on list/skip_list.go
> +type SkipList[T any] struct {
skiplist好像不能支持很多list接口相关的方法，像Append(ts ...T) error，Add(index int, t T) error，Set(index int, t T) error， 我不知自己理解的对不对

2023-10-16 12:35 UTC, AIJoe1995 commented on list/skip_list.go
> +type SkipList[T any] struct {
skip_list应该没办法实现List接口，skip list是有序的，List接口里面Append方法向后追加不能保证有序了，还有Add(index int, t T) error，Set(index int, t T) error

2023-10-17 00:39 UTC, flyhigher139 commented
> > 我也写过一个跳表的实现，虽说大差不差，不过我觉得也可以借鉴一下有些写法或封装：
> > https://github.com/igevin/algokit/blob/master/collection/skiplist/skiplist.go
> 
> 帮着 review，我已经好久没写过了，人已经是一个废物了

好的，我今晚仔细看看，昨天大致看了一下，应该没啥问题的~

2023-10-17 12:56 UTC, flyhigher139 commented on internal/list/skip_list_test.go
> +	testCases := []struct {
删除的测试用例包括：

- 从空跳表中删除元素
- 从只有一个元素的跳表中删除，列表中有被删元素
- 从只有一个元素的跳表中删除，列表中没有被删元素
- 从多个元素的跳表中删除，列表中有被删元素
- 从多个元素的跳表中删除，列表中没有被删元素

2023-10-17 12:56 UTC, flyhigher139 commented on internal/list/skip_list_test.go
> +	testCases := []struct {
测试用例包括：
- 向空跳表插入数据
- 向非空跳表插入数据
- 向跳表插入重复数据

2023-10-17 12:56 UTC, flyhigher139 commented on internal/list/skip_list.go
> +	}
106~111行代码，有好几个地方都用到，是重复代码，可以提炼一个traverse()方法出来共用

2023-10-17 13:06 UTC, flyhigher139 commented on internal/list/skip_list.go
> +// levels的生成和跳表中元素个数无关
randomLevel 我是这么写的，应该效率更高，可以参考一下
```go

const (
	maxLevel = 32 // 跳表的最大层级为 32
	branch   = 4  // 每隔几个节点，建一级索引；随机代码层数的算法中，表示概率 p = 1/4
)


// randomLevel 返回一个随机的层高.
// Skip List的论文中，随机层数的伪代码为：
// RandomLevel():
//
//	lvl = 1
//	while random() < p and lvl < MaxLevel do
//		lvl+=1
//	return lvl
//
// 其中，p的意思为：节点有第i层指针，那么第i+1层出现的概率为p
// redis 中，p = 1/4, maxLevel = 64
func randomLevel() int {
	level := 1
	for level < maxLevel && (rand.Int31()&0xFFFF)%branch == 0 {
		level += 1
	}
	return level
}
```

2023-10-18 13:37 UTC, AIJoe1995 commented on internal/list/skip_list.go
> +// levels的生成和跳表中元素个数无关
谢谢~我修改一下

2023-10-21 03:38 UTC, AIJoe1995 commented on internal/list/skip_list.go
> +	if node == nil || sl.compare(node.Val, target) != 0 {
嗯嗯，这个刚改成true了

2023-10-21 03:42 UTC, AIJoe1995 commented on internal/list/skip_list.go
> +	for (rand.Int31() & 0xFFFF) < int32(p*0xFFFF) {
这个我做了100万次循环，现在的写法比之前的快很多，应该是以前求rand的时候比较慢。现在的写法和(rand.Int31()&0xFFFF)%branch == 0的时间差不多。网上说redis里是这样写的while ((random()&0xFFFF)<(ZSKIPLST_P *0xFFFF) 虽然不知道为啥这样快了。

2023-10-22 15:09 UTC, flyhigher139 commented
@flycash @longyue0521 我没其他review意见了

2023-10-24 13:55 UTC, flyhigher139 commented on internal/list/skip_list_test.go
> +			wantRes:   false,
wantRes 应该是true

2023-10-24 14:23 UTC, AIJoe1995 commented
我不知道为什么那两个check过不了。。。能帮我看一下嘛

2023-10-24 14:24 UTC, AIJoe1995 commented on internal/list/skip_list_test.go
> +			wantRes:   false,
忘记改了，谢谢~

2023-10-25 01:11 UTC, longyue0521 commented
@flycash 
skip list若要实现List接口中带索引的操作会降低效率 比如:Add(index int, t T) error，Set(index int, t T) error, Delete等. 若不实现则作为list的实现放在list包中又不太好, 因为list/types.go定义了抽象接口. 是否重新规划一个目录? 或者将其保留在internal包中, 然后基于该skip list来实现map/set包中的接口?

2023-10-25 01:13 UTC, longyue0521 commented
@AIJoe1995 你要点开后面的`Details`去看一下具体提示信息.

Format Go code中的问题是你要先在本地执行一下`make setup`再执行`make check`

2023-10-25 03:20 UTC, AIJoe1995 commented
运行了make check之后，git status很多文件都被标成Modified了，应该把这些文件都git add git commit吗？

2023-10-25 03:38 UTC, longyue0521 commented
> 运行了make check之后，git status很多文件都被标成Modified了，应该把这些文件都git add git commit吗？

不要这样做 当前PR只应该包含与其相关的代码

1. 同步最新代码: git pull --rebase upstream dev, 其中upstream表是github.com/ecodeclub/ekit
2. make setup // 不该修改代码
3. make check
4. 提交

2023-10-25 06:30 UTC, AIJoe1995 commented
我执行了下面的命令, 这样执行对吗？ make check 之后还是很多文件Modified了,应该怎么处理啊 
1. 删除了本地的ekit文件夹
2. 把我的repo里的ekit重新拉下来了 git clone git@github.com:AIJoe1995/ekit.git
3. git remote add upstream https://github.com/ecodeclub/ekit.git 
4. git pull --rebase upstream dev 
5. git status 和 git branch -av 的结果
![image](https://github.com/ecodeclub/ekit/assets/87262545/f6f318ad-0a4f-4283-8ca8-b85cd206c441)

6. 然后执行了git merge
7. git push 

![image](https://github.com/ecodeclub/ekit/assets/87262545/df529bbc-753f-4793-85d7-e4564cef8a28)

8. make setup
9. git status （执行了make setup之后 git status是nothing to commit） 
10. make check 
11. git status 执行了make check之后 git status里有很多文件标记成Modified 

![image](https://github.com/ecodeclub/ekit/assets/87262545/9f07cfcc-f517-4fe7-bbb8-f8ccc2b2ca4f)

2023-10-25 07:02 UTC, longyue0521 commented
你可以做实验来排查
1. 直接将ecodeclub/ekit克隆下来 然后执行make setup , make check , 按理说应该没有任何修改
2. 在你上面的步骤5处 执行make setup, make check, 看看文件是否有改变

2023-10-25 07:19 UTC, AIJoe1995 commented
直接将ecodeclub/ekit克隆下来 然后执行make setup , make check。 make check之后git status有很多Modified文件。
1. mkdir ecodeclub 
2. cd ecodeclub 
3. git clone https://github.com/ecodeclub/ekit.git
4. cd ekit 
5. git status (git status是nothing to commit)
6. make setup 
7. git status (make setup之后git status 是nothing to commit )
8. make check 
9. git status (make check 之后git status 有 changed not staged for commit 

![image](https://github.com/ecodeclub/ekit/assets/87262545/b454cf14-f1d5-4727-8302-da430ea1851b)
![image](https://github.com/ecodeclub/ekit/assets/87262545/90c46f4b-a4c7-4a05-9b40-86bae3599eef)

2023-10-25 08:50 UTC, longyue0521 commented
我在自己的mac上实验了一下,结果符合预期,但与你的不同:
![image](https://github.com/ecodeclub/ekit/assets/6337745/56e68918-8d18-4bb9-9227-64f88eeb5232)

![image](https://github.com/ecodeclub/ekit/assets/6337745/8cf060d5-0c5e-49bc-bb4d-ff92eb62cfec)


go/src是一个比较特殊的目录,换一个地方试试呢? 比

2023-10-25 11:01 UTC, AIJoe1995 commented
make check之后很多文件被标为Modified好像是因为windows的CRLF换行符。 
我设置git config --global core.autocrlf false 之后，又重新拉下来[AIJoe1995/ekit](https://github.com/AIJoe1995/ekit)的最新commit,做make setup make check, 在本地git status之后 只有internal/list/skip_list.go一个文件不一样了， 不一样的地方是，make check之后 会比原先的多了一个空行
![image](https://github.com/ecodeclub/ekit/assets/87262545/63ca290b-9846-4af6-a542-91da79164b89)
然后我git add  ./internal/list/skip_list.go
git commit 了

2023-10-26 14:22 UTC, flycash commented on internal/list/skip_list.go
> +	for (rand.Int31() & 0xFFFF) < int32(p*0xFFFF) {
只能说，一代更比一代骚

2023-10-26 14:23 UTC, flycash reviewed
在对应的 skip_list 也写个简单的测试。因为本身你是依托于 internal 里面的代码，所以这里你可以写得简单一些。

2023-10-27 01:48 UTC, AIJoe1995 commented
好的，todo测试， 那skip_list是不是还要调整一下实现的方法，要实现哪个接口比较好

2023-10-27 02:49 UTC, longyue0521 commented
> 在对应的 skip_list 也写个简单的测试。因为本身你是依托于 internal 里面的代码，所以这里你可以写得简单一些。

@flycash  skip list若要实现List接口中带索引的操作会降低效率 比如:Add(index int, t T) error，Set(index int, t T) error, Delete等. 若不实现则作为list的实现放在list包中又不太好, 因为list/types.go定义了抽象接口. 是否重新规划一个目录? 或者将其保留在internal包中, 然后基于该skip list来实现map/set包中的接口?

2023-11-06 09:24 UTC, flycash commented
> > 在对应的 skip_list 也写个简单的测试。因为本身你是依托于 internal 里面的代码，所以这里你可以写得简单一些。
> 
> @flycash skip list若要实现List接口中带索引的操作会降低效率 比如:Add(index int, t T) error，Set(index int, t T) error, Delete等. 若不实现则作为list的实现放在list包中又不太好, 因为list/types.go定义了抽象接口. 是否重新规划一个目录? 或者将其保留在internal包中, 然后基于该skip list来实现map/set包中的接口?

这个需要引入一个新的 sorted list 之类的接口。 skiplist 这边暂时这样，我们还没发版，所以后面也可以改。

2023-11-06 09:24 UTC, flycash approved these changes

2023-11-06 09:24 UTC, flycash commented on internal/list/skip_list.go
> +	MaxLevel = 32
优先做成私有的

2023-11-06 10:53 UTC, longyue0521 approved these changes

2023-11-06 10:54 UTC, merged