重构: randx.RandCode 代码
ecodeclub/ekit pull request #241
Opened 2024-01-12 14:44 UTC by dxyinme

1. 支持字符类型自由组合
2. 增加对特殊字符的支持
3. 增加函数RandStrByCharset，可以自定义字符集
4. 增加对length小于0的异常处理

2024-01-13 03:59 UTC, longyue0521 requested changes

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code.go
> +	typeCharSetPair = []pair.Pair[TYPE, string]{
typeCharPairSet

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code.go
> +}
1. 在注释中明确一下RandCode和RandStrByCharset中length取值范围, charset的范围等
2. 代码中length <= 0的情况可以提前检查, 对于RandCode来说即便底层调用RandStrByCharset, 也可以通过提前检查来加速

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code.go
> +	TYPE_LETTER TYPE = TYPE_LOWER
这是为了兼容之前的实现吗? TYPE_LOWER_LETTER, TYPE_UPPER_LETTER更容理解一些

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code_test.go
> +		},
缺少length=0的测试用例

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code_test.go
> +		{
缺少length=0的测试用例

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code_test.go
> +			}
if err != nil {
 // 执行断言
 return
}
// err == nil 情况下要执行的断言

2024-01-13 03:59 UTC, longyue0521 commented on randx/rand_code_test.go
> +			}
另外, testify的错误信息会包含类似于 "expected length: %d but got length:%d",tc.length, len(code) 的提示信息, 所以你可以直接简写assert.Len(t, code, tc.length)之类的

2024-01-13 08:16 UTC, dxyinme commented on randx/rand_code.go
> +	TYPE_LETTER TYPE = TYPE_LOWER
是的。是为了兼容之前的实现，LOWERCASE / UPPERCASE会不会更好？

2024-01-13 08:18 UTC, dxyinme commented on randx/rand_code.go
> +	typeCharSetPair = []pair.Pair[TYPE, string]{
认真考虑了一下，应该改为typeCharsetPairs 更合适一点 charset是字符集的意思

2024-01-13 08:42 UTC, dxyinme commented on randx/rand_code.go
> +	TYPE_LETTER TYPE = TYPE_LOWER
使用 LOWERCASE / UPPERCASE 了

2024-01-13 08:42 UTC, dxyinme commented on randx/rand_code.go
> +}
已增加

2024-01-13 08:53 UTC, flycash reviewed
我有一个小问题，就是有没有必要同时暴露 RandCode 和 RandStrCahrset 两个方法？

比如说，我不暴露 RandCode，我直接暴露 RandStrCharset，那么我直接用 RandStrCharset 会有什么问题吗？

2024-01-13 08:53 UTC, flycash commented on randx/rand_code.go
> +	ERRTYPENOTSUPPORTTED = ErrTypeNotSupported
暂时都设置为私有的，目前来看，没有暴露出去的必要。之前 ERRTYPENOTSUPPORTTED 也还没发布正式版本，所以改了也没关系

2024-01-13 09:02 UTC, dxyinme commented on randx/rand_code.go
> +	ERRTYPENOTSUPPORTTED = ErrTypeNotSupported
好的

2024-01-13 09:04 UTC, dxyinme commented
> 我有一个小问题，就是有没有必要同时暴露 RandCode 和 RandStrCahrset 两个方法？
> 
> 比如说，我不暴露 RandCode，我直接暴露 RandStrCharset，那么我直接用 RandStrCharset 会有什么问题吗？

不会有什么问题，RandCode的存在只是给RandStrByCharset做了一个封装，个人感觉还是可以保留的，为了给使用者带来方便，他们可以直接使用RandCode，而不需要自己拼凑字符集

2024-01-13 09:29 UTC, flycash approved these changes

2024-01-14 11:29 UTC, longyue0521 approved these changes

2024-01-14 11:29 UTC, merged