slice.Reverse, slice.Add, arrayList.Add 修改
ecodeclub/ekit pull request #242
Opened 2024-01-17 12:27 UTC by dxyinme

1. 增加slice.Reverse对any类型的支持
2. arrayList的add方法直接使用slice.Add
3. 让slice.Add可以支持往末尾添加元素

2024-01-18 02:39 UTC, longyue0521 requested changes

2024-01-18 02:39 UTC, longyue0521 commented on slice/add.go
> +// 如果index == len(src) 则表示往末尾添加元素
slice.Add在这里被使用的话,这个修改就变为一个“不兼容”的修改 —— 之前用户在len(src)位置添加元素会得到一个错误,现在不会了.

需要 @flycash 确认一下

2024-01-18 02:39 UTC, longyue0521 commented on slice/reverse.go
> +func Reverse[T any](src []T) []T {
从comparable -> any,类型范围变大,属于兼容性修改,Reverse相关的修改应该没问题

2024-01-18 02:39 UTC, longyue0521 commented on slice/reverse_test.go
> +			res := Reverse[testStruct](tt.src)
这里还要补充一个断言 —— res 和 tt.src 不是同一个对象, 好像有一个assert.Same之类的可以做到. 请将上面的TestReverseInt一并修改.

2024-01-18 13:11 UTC, dxyinme commented on slice/add.go
> +// 如果index == len(src) 则表示往末尾添加元素
感觉这可能是那时候design的时候没考虑到，毕竟arrayList的Add都支持append

2024-01-19 01:27 UTC, longyue0521 commented on slice/add.go
> +// 如果index == len(src) 则表示往末尾添加元素
那应该是types.go中抽象接口中的方法语义没描述好,毕竟arrayList也是实现types.go中的接口,要不你将types.go中对应的方法的注释也修改一下. 然后再等等 @flycash 的确认

2024-01-19 01:27 UTC, longyue0521 approved these changes

2024-01-19 15:54 UTC, dxyinme commented on slice/add.go
> +// 如果index == len(src) 则表示往末尾添加元素
已修改

2024-01-21 15:18 UTC, flycash reviewed
没有什么问题，我觉得保持 append 语义才是我想要的。

2024-01-21 15:18 UTC, flycash commented on slice/add.go
> +// 如果index == len(src) 则表示往末尾添加元素
我设计之初就想使用 append 语义的。我记得这边当初 len 应该是可以的。原本的条件是：
```go
if index < 0 || index > len(a.vals) {
```
看起来应该是兼容的

2024-01-21 15:18 UTC, flycash commented on list/array_list.go
> +	if a.vals, err = slice.Add(a.vals, t, index); err != nil {
这样直接就可以了？
```go
a.vals, err = slice.Add()
return 
```

2024-01-21 16:38 UTC, dxyinme commented on list/array_list.go
> +	if a.vals, err = slice.Add(a.vals, t, index); err != nil {
确实是，我后面改一下

2024-01-22 11:15 UTC, dxyinme commented on list/array_list.go
> +	if a.vals, err = slice.Add(a.vals, t, index); err != nil {
已修复

2024-01-22 11:15 UTC, dxyinme commented on slice/add.go
> +// 如果index == len(src) 则表示往末尾添加元素
已修复

2024-01-22 11:31 UTC, longyue0521 approved these changes

2024-01-22 11:32 UTC, merged